void idlDummy();

/*
[Entity=Class]
interface IDLDummyClass {
    void dummy();
};
*/

interface SampleI {
    attribute boolean flag;
    boolean isSupported();
};

interface SampleC {
    attribute boolean flag;
    boolean isSupported();
};

SampleI getSampleI();
SampleC getSampleC();
