package arkui.component.stage_extender;


// TBD: Used in dummy_impl.cpp
enum PageTransitionType {
    number ENTER = 0;
    number EXIT = 1;
};

// TBD: Used in dummy_impl.cpp
enum RouteType {
    [OriginalEnumMemberName=None]
    number NONE = 0;
    [OriginalEnumMemberName=Push]
    number PUSH = 1;
    [OriginalEnumMemberName=Pop]
    number POP = 2;
};

// TBD: Used in dummy_impl.cpp
interface PageTransitionOptions {
    [Optional]
    attribute RouteType type;
    [Optional]
    attribute i32 duration;
    [Optional]
    attribute i32 delay;
};
callback PageTransitionCallback = void (RouteType type, f64 progress);

// TBD: Used in dummy_impl.cpp
[Entity=Interface]
interface TransitionParam {
    attribute PageTransitionOptions pageTransitionOptions;
    attribute PageTransitionType pageTransitionType;

    [Optional]
    attribute RouteType routeType;

    [Optional]
    attribute PageTransitionCallback onProgress;
};

// TBD: Used in dummy_impl.cpp
[Entity=Class]
interface StageExtender {
  static void SetSrcPage(pointer node);
  static void PushPage(pointer node);
  static void PopPageAndSwitchTo(pointer node);
  static void ResetTransitions(pointer node);
  static void SetPageTransition(pointer node, TransitionParam param);
};