package global.resource;
interface Resource {
    attribute String bundleName;
    attribute String moduleName;
    attribute i64 id;
    [Optional]
    attribute sequence<(String or i32 or i64 or f64 or Resource)> params;
    [Optional]
    attribute i32 type;
};