/*
 * Copyright (c) 2024-2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

dictionary HuksTag {
    number HUKS_TAG_INVALID = 0;
    number HUKS_TAG_ALGORITHM = 536870913;
    number HUKS_TAG_PURPOSE = 536870914;
    number HUKS_TAG_KEY_SIZE = 536870915;
};

interface HuksParam {
    attribute HuksTag tag;
    attribute (boolean or number) value;
};

interface HuksOptions {
    [Optional]
    attribute sequence<HuksParam> properties;
};
