# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("./gn/import/npm.gni")
import("./gn/import/node.gni")

if (current_toolchain == host_toolchain) {
    npm_install("npm_install_all") {
        deps = [
            "${koala_mr.root_path}:npm_install_all"
        ]
        outputs = [
            "$target_out_dir/npm_install_all"
        ]
        project_path = rebase_path(".")
    }
}

group("all") {
    deps = [
        "arkgen:all",
        "ohosgen:all",
        "runner:all",
        "core:all",
        "libohos:all",
        "dtsgen:all",
        "etsgen:all",
        "idlinter:all",
        "interfaces:all",
        "tools:all",
    ]
}
