/*
 * Copyright (c) 2022-2023 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#pragma once

#ifdef KOALA_USE_ARK_VM_WITH_JS
#include "convertors-node-internal.h"

#define KOALA_INTEROP_0 NODEJS_API_0
#define KOALA_INTEROP_1 NODEJS_API_1
#define KOALA_INTEROP_2 NODEJS_API_2
#define KOALA_INTEROP_3 NODEJS_API_3
#define KOALA_INTEROP_4 NODEJS_API_4
#define KOALA_INTEROP_5 NODEJS_API_5
#define KOALA_INTEROP_6 NODEJS_API_6
#define KOALA_INTEROP_7 NODEJS_API_7
#define KOALA_INTEROP_8 NODEJS_API_8
#define KOALA_INTEROP_9 NODEJS_API_9
#define KOALA_INTEROP_10 NODEJS_API_10
#define KOALA_INTEROP_11 NODEJS_API_11
#define KOALA_INTEROP_12 NODEJS_API_12
#define KOALA_INTEROP_13 NODEJS_API_13
#define KOALA_INTEROP_14 NODEJS_API_14
#define KOALA_INTEROP_V0 NODEJS_API_V0
#define KOALA_INTEROP_V1 NODEJS_API_V1
#define KOALA_INTEROP_V2 NODEJS_API_V2
#define KOALA_INTEROP_V3 NODEJS_API_V3
#define KOALA_INTEROP_V4 NODEJS_API_V4
#define KOALA_INTEROP_V5 NODEJS_API_V5
#define KOALA_INTEROP_V6 NODEJS_API_V6
#define KOALA_INTEROP_V7 NODEJS_API_V7
#define KOALA_INTEROP_V8 NODEJS_API_V8
#define KOALA_INTEROP_V9 NODEJS_API_V9
#define KOALA_INTEROP_V10 NODEJS_API_V10
#define KOALA_INTEROP_V11 NODEJS_API_V11
#define KOALA_INTEROP_V12 NODEJS_API_V12
#define KOALA_INTEROP_V13 NODEJS_API_V13
#define KOALA_INTEROP_V14 NODEJS_API_V14

#elif KOALA_USE_ARK_VM_WITH_ETS // !KOALA_USE_ARK_VM_WITH_JS 

#include "ets/convertors-ets.h"
#include "ets/vm/etsapi/etsapi.h"

#define KOALA_INTEROP_0 ETS_API_0
#define KOALA_INTEROP_1 ETS_API_1
#define KOALA_INTEROP_2 ETS_API_2
#define KOALA_INTEROP_3 ETS_API_3
#define KOALA_INTEROP_4 ETS_API_4
#define KOALA_INTEROP_5 ETS_API_5
#define KOALA_INTEROP_6 ETS_API_6
#define KOALA_INTEROP_7 ETS_API_7
#define KOALA_INTEROP_8 ETS_API_8
#define KOALA_INTEROP_9 ETS_API_9
#define KOALA_INTEROP_10 ETS_API_10
#define KOALA_INTEROP_11 ETS_API_11
#define KOALA_INTEROP_12 ETS_API_12
#define KOALA_INTEROP_13 ETS_API_13
#define KOALA_INTEROP_14 ETS_API_14
#define KOALA_INTEROP_V0 ETS_API_V0
#define KOALA_INTEROP_V1 ETS_API_V1
#define KOALA_INTEROP_V2 ETS_API_V2
#define KOALA_INTEROP_V3 ETS_API_V3
#define KOALA_INTEROP_V4 ETS_API_V4
#define KOALA_INTEROP_V5 ETS_API_V5
#define KOALA_INTEROP_V6 ETS_API_V6
#define KOALA_INTEROP_V7 ETS_API_V7
#define KOALA_INTEROP_V8 ETS_API_V8
#define KOALA_INTEROP_V9 ETS_API_V9
#define KOALA_INTEROP_V10 ETS_API_V10
#define KOALA_INTEROP_V11 ETS_API_V11
#define KOALA_INTEROP_V12 ETS_API_V12
#define KOALA_INTEROP_V13 ETS_API_V13
#define KOALA_INTEROP_V14 ETS_API_V14
#endif  // KOALA_USE_ARK_VM_WITH_ETS

#define KOALA_INTEROP_CALL_VOID NODEJS_API_CALL_VOID
#define KOALA_INTEROP_CALL_INT NODEJS_API_CALL_INT
#define KOALA_INTEROP_CTX_1 NODEJS_API_CTX_1
#define KOALA_INTEROP_CTX_2 NODEJS_API_CTX_2
#define KOALA_INTEROP_CTX_3 NODEJS_API_CTX_3
