ohosgen XML demo:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    needs:
    - build idlize
    before_script:
      - !reference [.npm, script]
    script:
      - cd $CI_PROJECT_DIR/ohosgen/tests/demos/xml
      - npm run all:ts
      - npm run all:arkts

<Kotlin> ohosgen XML demo:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    needs:
      - build idlize
      - download koala_projects
    before_script:
      - !reference [.npm, script]
      - npm i -C external/koala_projects/tools --prefer-offline --no-audit --no-fund
    script:
      - cd $CI_PROJECT_DIR/ohosgen/tests/demos/xml
      - npm run all:kt

ohosgen unit tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
  before_script:
    - !reference [.npm, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/unit
    - npm run all:ts
    - npm run all:arkts
    - cd $CI_PROJECT_DIR/ohosgen/tests/dummy
    - npm run all:ts
    - npm run all:arkts
  # after_script:
  #   - !reference [.notify-telegram, script]

<Kotlin> ohosgen unit tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
    - download koala_projects
  before_script:
    - !reference [.npm, script]
    - npm i -C external/koala_projects/tools --prefer-offline --no-audit --no-fund
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/unit
    - npm run all:kt

ohosgen OST tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
  before_script:
    - !reference [.npm, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/ost
    - npm run all:arkts

ohosgen demos:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
  - build idlize
  before_script:
    - !reference [.npm, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/demos/mediaquery
    - npm show @koalaui/interop && npm show @koalaui/common
    - npm run all:ts
    - npm run all:arkts
    - cd $CI_PROJECT_DIR/ohosgen/tests/demos/context
#   - npm run all:ts
    - npm run all:arkts
    - cd $CI_PROJECT_DIR/ohosgen/tests/demos/huks
    - npm run all:ts
    - npm run all:arkts

ohosgen system tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
  before_script:
    - !reference [.npm, script]
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/system
    - npm i -d
    - python3 run-system-tests.py arkts

<Kotlin> ohosgen system tests:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
    - download koala_projects
  before_script:
    - !reference [.npm, script]
    - npm i -C external/koala_projects/tools --prefer-offline --no-audit --no-fund
  script:
    - cd $CI_PROJECT_DIR/ohosgen/tests/system
    - npm i -d
    - python3 run-system-tests.py kt
