# Copyright (c) 2025 Huawei Device Co., Ltd.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("../../../gn/import/idlize_root.gni")
import("${idlize_root}/gn/import/bash.gni")
import("${idlize_root}/gn/import/node.gni")
import("${idlize_root}/gn/import/npm.gni")


template("unit_test") {
    test_target_name = target_name
    vm_data = invoker.vm
    test_vm = vm_data.vm
    language = vm_data.language

    rm("$test_target_name:clean") {
        recursive = true
        force = true
        file = [
            rebase_path("./generated/$language"),
            rebase_path("$target_gen_dir/$language")
        ]
        deps = [ "${idlize_root}/ohosgen:compile" ]
    }

    node_cmd("$test_target_name:generate") {
        script = rebase_path("../..")
        args = [
            "--idl2peer",
            "--language=$language",
            "--default-idl-package",
            "unit",
            "--input-dir",
            rebase_path("./idl"),
            "--output-dir",
            rebase_path("$target_gen_dir/$language"),
            "--options-file",
            rebase_path("conf/config.json")
        ]
        outputs = [
            "$target_gen_dir/$language/generated/native/unit.cpp",
            "$target_gen_dir/$language/generated/native/unitApiImpl_temp.cpp"
        ]
        deps = [
            ":$test_target_name:clean",
            "${idlize_root}/dtsgen:compile",
            "${idlize_root}/ohosgen:compile"
        ]
    }

    cp("${test_target_name}:generate:cp") {
        src = [ rebase_path("$target_gen_dir/$language/generated/$language") ]
        dest = rebase_path("./generated/")
        deps = [
            ":$test_target_name:generate",
        ]
    }

    npm_cmd("$test_target_name:compile") {
        _lang_short = language
        if (_lang_short == "kotlin") {
            _lang_short = "kt"
        }
        project_path = rebase_path(".")
        run_tasks = [ "compile:${_lang_short}" ]
        deps = [
            ":$test_target_name:generate",
            ":${test_target_name}:generate:cp",
            "${idlize_root}:external_libarkts",
        ]
    }

    _output_dir = "$target_out_dir/$test_vm"
    lib_name = "UNITNativeModule"

    shared_library("${test_target_name}:compile:native") {
        _interop_dir = "${idlize_root}/node_modules/@koalaui/interop/src/cpp"
        _interop_build_dir = "${idlize_root}/node_modules/@koalaui/interop/build"
        sources = [
            "$target_gen_dir/$language/generated/native/unit.cpp",
            "$target_gen_dir/$language/generated/native/unitApiImpl_temp.cpp",
            "src/cpp/unitImpl.cpp",
        ]
        cflags = [ "-DKOALA_LIBACE_LINKED" ]
        ldflags = []
        include_dirs = [
            "$target_gen_dir/$language/generated/native",
            "src/cpp",
            _interop_dir,
            "$_interop_dir/types",
        ]

        if (target_os == "win") {
            cflags += [ "-DKOALA_WINDOWS" ]
        }
        if (target_os == "linux") {
            cflags += [ "-DKOALA_LINUX" ]
        }
        if (target_os == "mac") {
            cflags += [ "-DKOALA_MACOS" ]
        }

        if (current_toolchain == "//gn/toolchain:clang") {
            # Improve: remove all -Wno-* when generation is fixed.
            cflags += [
                "-Wall", "-Werror", "-Wno-unused-variable", "-Wno-unused-but-set-variable",
                "-Wno-extern-c-compat", "-Wno-error=deprecated-declarations",
                "-Wno-unknown-warning-option", "-Wno-unused-function", "-Wno-macro-redefined",
                "-Wno-enum-compare", "-Wno-tautological-constant-out-of-range-compare"
            ]
        } else if (current_toolchain == "//gn/toolchain:msvc") {
            # Avoid using COMDAT to not exceed COFF file limits, see https://learn.microsoft.com/en-us/cpp/error-messages/compiler-errors-1/fatal-error-c1128?view=msvc-170
            cflags += [ "/Gy-" ]
        } else {
            assert(false, "Compile flags for current toolchain $current_toolchain are not defined")
        }

        if (test_vm == "node") {
            sources += [
                "${_interop_dir}/napi/convertors-napi.cpp"
            ]
            if (target_os == "win") {
                sources += [ "${_interop_dir}/napi/win-dynamic-node.cpp" ]
            }

            cflags += [
                "-DKOALA_USE_NODE_VM",
                "-DKOALA_NAPI",
                "-DINTEROP_LIBRARY_NAME=${lib_name}"
            ]
            ldflags += [ rebase_path("${_interop_build_dir}/InteropNativeModule.node") ]
            _node_api_headers = "${idlize_root}/node_modules/node-api-headers"
            include_dirs += [
                "${_node_api_headers}/include",
                "${_interop_dir}/napi"
            ]
            output_extension = "node"
        } else if (test_vm == "panda") {
            sources += [
                "${_interop_dir}/ani/convertors-ani.cpp",
                "${_interop_dir}/types/signatures.cpp"
            ]
            cflags += [
                "-DKOALA_USE_PANDA_VM",
                "-DKOALA_ANI",
                "-DINTEROP_LIBRARY_NAME=${lib_name}",
                "-DETS_MODULE_CLASSPATH_PREFIX=@unit.generated.arkts.unit.INTERNAL.",
            ]
            _interop_build_dir = "${idlize_root}/node_modules/@koalaui/interop/build"
            ldflags += [ rebase_path("${_interop_build_dir}/libInteropNativeModule.so") ]
            include_dirs += [
                "${_interop_dir}/ani",
                "${_interop_dir}/ani/panda",
            ]
        } else if (test_vm == "cangjie") {
            sources += [
                "${_interop_dir}/cangjie/convertors-cj.cpp",
                "${_interop_dir}/types/signatures.cpp"
            ]
            cflags += [
                "-DKOALA_CJ",
                "-DINTEROP_LIBRARY_NAME=${lib_name}",
            ]
            include_dirs += [
                "${_interop_dir}/cangjie",
            ]
        }
        output_name = lib_name
        output_dir = _output_dir
        output_prefix_override = (test_vm == "node")
        deps = [
            "${idlize_root}:external_interop_panda",
            "${idlize_root}:external_interop_node",
            ":$test_target_name:generate"
        ]
        if (test_vm == "node") {
            deps += [ "${idlize_root}:external_interop_native_node" ]
        } else {
            deps += [ "${idlize_root}:external_interop_native_panda" ]
        }
    }
    
    cp("${test_target_name}:install:native") {
        _platform_build_dir = "build"
        if (test_vm == "node") {
            _platform_build_dir += "/node"
        } else if (test_vm == "panda") {
            _platform_build_dir += "/panda"
        } else if (test_vm == "cangjie") {
            _platform_build_dir += "/cangjie"
        }
        _name_prefix = ""
        if (test_vm != "node" && target_os != "win") {
            _name_prefix = "lib"
        }
        _name_suffix = ".so"
        if (test_vm == "node") {
            _name_suffix = ".node"
        } else if (target_os == "win") {
            _name_suffix = ".dll"
        } else if (target_os == "mac") {
            _name_suffix = ".dylib"
        }
        _full_output_name = "${_name_prefix}${lib_name}${_name_suffix}"
        src = [ rebase_path("${_output_dir}/${_full_output_name}") ]
        dest = rebase_path("${_platform_build_dir}/${_full_output_name}")
        deps = [
            ":${test_target_name}:compile:native",
        ]
    }

    bash_cmd(test_target_name) {
        script = "./scripts/"
        if (test_vm == "node") {
            script += "run-ts.sh"
        } else if (test_vm == "panda") {
            script += "run-panda.sh"
        } else if (test_vm == "cangjie") {
            script += "run-cj.sh"
        } else {
            script += "run-kt.sh"
        }
        script = rebase_path(script)
        deps = [
            ":${test_target_name}:compile",
            ":${test_target_name}:compile:native",
            ":${test_target_name}:install:native"
        ]
    }
}

vms = [
    { vm = "node"
      language = "ts" },
    { vm = "panda"
      language = "arkts" },
]

target_names = []

foreach(_vm, vms) {
    test_name = "check:${_vm.vm}"
    unit_test(test_name) {
        vm = _vm
    }
    target_names += [ ":$test_name" ]
}

group("all") {
    deps = target_names
}
