package ohos.base;

[TypeParameters="T"]
callback Callback = void (T data);
[TypeParameters="T", TypeParametersDefaults="void"]
interface BusinessError {
    attribute String name;
    attribute String message;
    [Optional]
    attribute String stack;
    attribute i32 code;
    attribute T data;
};