
export const CONST_BOOLEAN_FALSE = false;
export const CONST_BOOLEAN_TRUE = true;
export const CONST_NUMBER_INT = 312;
export const CONST_NUMBER_FLOAT = 312.415;
export const CONST_STRING = "hello_string";

export const CONST_TYPE_BOOLEAN: boolean;
export const CONST_TYPE_NUMBER: number;
export const CONST_TYPE_FLOAT: float;
export const CONST_TYPE_STRING: string;

export namespace const_ns {

    export const CONST_BOOLEAN_FALSE = false;
    export const CONST_BOOLEAN_TRUE = true;
    export const CONST_NUMBER_INT = 312;
    export const CONST_NUMBER_FLOAT = 312.415;
    export const CONST_STRING = "hello_string";

    export const CONST_TYPE_BOOLEAN: boolean;
    export const CONST_TYPE_NUMBER: number;
    export const CONST_TYPE_FLOAT: float;
    export const CONST_TYPE_STRING: string;
}