package arkui.component.idlize;
import ohos.base.AsyncCallback as AsyncCallback;
import ohos.router.default as router;

callback RouterFinishCallback = void (pointer value);

interface PageRouterOptions {
  attribute router.RouterOptions options;
  [Optional]
  attribute router.RouterMode mode;
};

[Entity=Class]
interface RouterExtender {
  static pointer push(pointer jsView, String url, optional boolean recover, optional RouterFinishCallback finishCallback);
  static pointer replace(pointer jsView, String url, optional boolean recover, optional RouterFinishCallback enterFinishCallback);
  static void moveCommonUnderPageNode(pointer commonNode, pointer pageNode);
  static void back();
  static void backWithOptions(String url, optional Object params);
  static pointer runPage(pointer jsView, String url, optional boolean recover, optional RouterFinishCallback finishCallback);
  static void clear();
  static void showAlertBeforeBackPage(String message);
  static void hideAlertBeforeBackPage();
  static Promise<void> pushNamedRoute(pointer jsView, PageRouterOptions options, optional RouterFinishCallback finishCallback);
  static void pushNamedRoute(pointer jsView, PageRouterOptions options, optional RouterFinishCallback finishCallback, optional [TypeArguments="void"] AsyncCallback callback_);
  static Promise<void> replaceNamedRoute(pointer jsView, PageRouterOptions options, optional RouterFinishCallback enterFinishCallback);
  static void replaceNamedRoute(pointer jsView, PageRouterOptions options, optional RouterFinishCallback finishCallback, optional [TypeArguments="void"] AsyncCallback callback_);
};