package arkui.component.idlize;

import arkui.component.common;

[Entity=Class]
interface AnimationExtender {
  static void OpenImplicitAnimation(AnimateParam param);
  static void CloseImplicitAnimation();
};