package arkui.component.idlize;

[Entity=Class]
interface LazyBuild {
    static void ApplyLazyBuilder();
    static void SetListItemLazyBuilder(pointer node, CustomBuilder builder);
    static void SetTabContentLazyBuilder(pointer node, CustomBuilder builder);
};