package arkui.component.idlize;

import arkui.component.button;
import arkui.component.checkbox;
import arkui.component.dataPanel;
import arkui.component.gauge;
import arkui.component.loadingProgress;
import arkui.component.progress;
import arkui.component.radio;
import arkui.component.rating;
import arkui.component.select;
import arkui.component.slider;
import arkui.component.textClock;
import arkui.component.textTimer;
import arkui.component.toggle;

[Synthetic]
callback ButtonModifierBuilder = pointer (pointer parentNode, ButtonConfiguration config);
[Synthetic]
callback CheckBoxModifierBuilder = pointer (pointer parentNode, CheckBoxConfiguration config);
[Synthetic]
callback DataPanelModifierBuilder = pointer (pointer parentNode, DataPanelConfiguration config);
[Synthetic]
callback GaugeModifierBuilder = pointer (pointer parentNode, GaugeConfiguration config);
[Synthetic]
callback LoadingProgressModifierBuilder = pointer (pointer parentNode, LoadingProgressConfiguration config);
[Synthetic]
callback ProgressModifierBuilder = pointer (pointer parentNode, ProgressConfiguration config);
[Synthetic]
callback RadioModifierBuilder = pointer (pointer parentNode, RadioConfiguration config);
[Synthetic]
callback RatingModifierBuilder = pointer (pointer parentNode, RatingConfiguration config);
[Synthetic]
callback MenuItemModifierBuilder = pointer (pointer parentNode, MenuItemConfiguration config);
[Synthetic]
callback SliderModifierBuilder = pointer (pointer parentNode, SliderConfiguration config);
[Synthetic]
callback TextClockModifierBuilder = pointer (pointer parentNode, TextClockConfiguration config);
[Synthetic]
callback TextTimerModifierBuilder = pointer (pointer parentNode, TextTimerConfiguration config);
[Synthetic]
callback ToggleModifierBuilder = pointer (pointer parentNode, ToggleConfiguration config);

[Entity=Class]
interface ContentModifierHelper {
    static void contentModifierButton(pointer node, ContentModifier<ButtonConfiguration> contentModifier, ButtonModifierBuilder builder);
    static void resetContentModifierButton(pointer node);
    static void contentModifierCheckBox(pointer node, ContentModifier<CheckBoxConfiguration> contentModifier, CheckBoxModifierBuilder builder);
    static void resetContentModifierCheckBox(pointer node);
    static void contentModifierDataPanel(pointer node, ContentModifier<DataPanelConfiguration> contentModifier, DataPanelModifierBuilder builder);
    static void resetContentModifierDataPanel(pointer node);
    static void contentModifierGauge(pointer node, ContentModifier<GaugeConfiguration> contentModifier, GaugeModifierBuilder builder);
    static void resetContentModifierGauge(pointer node);
    static void contentModifierLoadingProgress(pointer node, ContentModifier<LoadingProgressConfiguration> contentModifier, LoadingProgressModifierBuilder builder);
    static void resetContentModifierLoadingProgress(pointer node);
    static void contentModifierProgress(pointer node, ContentModifier<ProgressConfiguration> contentModifier, ProgressModifierBuilder builder);
    static void resetContentModifierProgress(pointer node);
    static void contentModifierRadio(pointer node, ContentModifier<RadioConfiguration> contentModifier, RadioModifierBuilder builder);
    static void resetContentModifierRadio(pointer node);
    static void contentModifierRating(pointer node, ContentModifier<RatingConfiguration> contentModifier, RatingModifierBuilder builder);
    static void resetContentModifierRating(pointer node);
    static void contentModifierMenuItem(pointer node, ContentModifier<MenuItemConfiguration> contentModifier, MenuItemModifierBuilder builder);
    static void resetContentModifierMenuItem(pointer node);
    static void contentModifierSlider(pointer node, ContentModifier<SliderConfiguration> contentModifier, SliderModifierBuilder builder);
    static void resetContentModifierSlider(pointer node);
    static void contentModifierTextClock(pointer node, ContentModifier<TextClockConfiguration> contentModifier, TextClockModifierBuilder builder);
    static void resetContentModifierTextClock(pointer node);
    static void contentModifierTextTimer(pointer node, ContentModifier<TextTimerConfiguration> contentModifier, TextTimerModifierBuilder builder);
    static void resetContentModifierTextTimer(pointer node);
    static void contentModifierToggle(pointer node, ContentModifier<ToggleConfiguration> contentModifier, ToggleModifierBuilder builder);
    static void resetContentModifierToggle(pointer node);
};