package arkui.component.idlize;
import arkui.component.common.KeyEvent as KeyEvent;
import arkui.component.Scroller as Scroller;

[Entity=Class]
interface IUIContext {
    static void freezeUINode(String id , boolean isFrozen );
    static void freezeUINode(i32 id , boolean isFrozen );
    static boolean dispatchKeyEvent((number or String) node, KeyEvent event);
    static async void openBindSheet(pointer bindSheetContent, optional SheetOptions sheetOptions, optional i32 targetId);
    static async void updateBindSheet(pointer bindSheetContent, SheetOptions sheetOptions, optional boolean partialUpdate);
    static async void closeBindSheet(pointer bindSheetContent);
    static void bindTabsToScrollable(TabsController tabsController, Scroller scroller);
    static void unbindTabsFromScrollable(TabsController tabsController, Scroller scroller);
    static void bindTabsToNestedScrollable(TabsController tabsController, Scroller parentScroller, Scroller scrollerchildScroller);
    static void unbindTabsFromNestedScrollable(TabsController tabsController, Scroller parentScroller, Scroller childScroller);
    static void setCustomKeyboardContinueFeature(CustomKeyboardContinueFeature feature);
};