package arkui.component.idlize;

import arkui.component.canvas.CanvasRenderingContext2D as CanvasRenderingContext2D;
import arkui.component.imageCommon.ImageAnalyzerConfig as ImageAnalyzerConfig;

[Entity=Class]
interface CanvasRenderingContext2DExtender {
    static Promise<void> startImageAnalyzer(CanvasRenderingContext2D peer, ImageAnalyzerConfig config);
};