package arkui.component.idlize;

import arkui.component.timePicker;
import arkui.component.textPicker;
import arkui.component.datePicker;

[Entity=Class]
interface DialogExtender {
  static void showTimePickerDialog(TimePickerDialogOptions options);
  static void showTextPickerDialog(TextPickerDialogOptions options);
  static void showDatePickerDialog(DatePickerDialogOptions options);
};