package arkui.component.idlize;

[Entity=Class]
interface DialogExtender {
  static void showTimePickerDialog(TimePickerDialogOptions options);
  static void showTextPickerDialog(TextPickerDialogOptions options);
  static void showDatePickerDialog(DatePickerDialogOptions options);
};