package arkui.component.idlize;

import arkui.component.common;
import ohos.arkui.UIContext;
import arkui.Graphics;
import arkui.FrameNode;
import arkui.RenderNode;

[Entity=Interface]
interface BorderRadiuses_graphics { // TODO must be removed when names collision problem is resolved
    attribute number topLeft;
    attribute number topRight;
    attribute number bottomLeft;
    attribute number bottomRight;
};
[Entity=Interface]
interface NodeEdgeStyles {
    attribute BorderStyle top;
    attribute BorderStyle right;
    attribute BorderStyle bottom;
    attribute BorderStyle left;
};
[Entity=Interface]
interface EdgeNumber {
    attribute number top;
    attribute number right;
    attribute number bottom;
    attribute number left;
};


[Entity=Class]
interface RenderNodeExtender {
  static pointer constructorRenderNode(i32 nodeId);
  static pointer getDestroy();
  static void destroyPeer(RenderNode peer);
  static void setBackgroundColor(RenderNode peer, number backgroundColor);
  static void setClipToFrame(RenderNode peer, boolean clipToFrame);
  static void setOpacity(RenderNode peer, number opacity);
  static void setSize(RenderNode peer, Size size, i32 unitValue);
  static void setPosition(RenderNode peer, Vector2 position, i32 unitValue);
  static void setPivot(RenderNode peer, Vector2 pivot);
  static void setScale(RenderNode peer, Vector2 scale);
  static void setTranslation(RenderNode peer, Vector2 translation);
  static void setRotation(RenderNode peer, Vector3 rotation, i32 unitValue);
  static void setTransform(RenderNode peer, Matrix4 transform);
  static void setShadowColor(RenderNode peer, number shadowColor);
  static void setShadowOffset(RenderNode peer, Vector2 shadowOffset, i32 unitValue);
  static void setLabel(RenderNode peer, String label);
  static void setShadowAlpha(RenderNode peer, number shadowAlpha);
  static void setShadowElevation(RenderNode peer, number shadowElevation);
  static void setShadowRadius(RenderNode peer, number shadowRadius);
  static void setBorderStyle(RenderNode peer, NodeEdgeStyles borderStyle);
  static void setBorderWidth(RenderNode peer, EdgeNumber borderWidth, i32 unitValue);
  static void setBorderColor(RenderNode peer, EdgeNumber borderColor);
  static void setBorderRadius(RenderNode peer, BorderRadiuses_graphics borderRadius, i32 unitValue);
  static void setMarkNodeGroup(RenderNode peer, boolean markNodeGroup);
  static void setRectMask(RenderNode peer, Rect rect, number fillColor, number strokeColor, number strokeWidth);
  static void setCircleMask(RenderNode peer, Circle circle, number fillColor, number strokeColor, number strokeWidth);
  static void setRoundRectMask(RenderNode peer, RoundRect roundRect,number fillColor, number strokeColor, number strokeWidth);
  static void setOvalMask(RenderNode peer, Rect rect, number fillColor, number strokeColor, number strokeWidth);
  static void setPath(RenderNode peer, CommandPath path, number fillColor, number strokeColor, number strokeWidth);
  static void setRectClip(RenderNode peer, Rect rect);
  static void setCircleClip(RenderNode peer, Circle circle);
  static void setRoundRectClip(RenderNode peer, RoundRect roundRect);
  static void setOvalClip(RenderNode peer, Rect rect);
  static void setPathClip(RenderNode peer, CommandPath path);
  static f64 appendChild(RenderNode peer, RenderNode node);
  static f64 insertChildAfter(RenderNode peer, RenderNode child, RenderNode sibling);
  static void removeChild(RenderNode peer, RenderNode node);
  static void clearChildren(RenderNode peer);
  static void invalidate(RenderNode peer);
};