package arkui.component.idlize; 

import arkui.component.common;
import arkui.component.pageTransition;

callback Callback_Extender_OnFinish = void ();

dictionary PageTransitionType {
    number ENTER = 0;
    number EXIT = 1;
};

[Entity=Interface]
interface TransitionParam {
    attribute PageTransitionOptions pageTransitionOptions;
    attribute PageTransitionType pageTransitionType;

    [Optional]
    attribute RouteType routeType;

    [Optional]
    attribute SlideEffect slideEffect;

    [Optional]
    attribute TranslateOptions translate;

    [Optional]
    attribute ScaleOptions scale;

    [Optional]
    attribute number opacity;

    [Optional]
    attribute PageTransitionCallback onProgress;

    [Optional]
    attribute Callback_Extender_OnFinish onFinish;
};

[Entity=Class]
interface StageExtender {
  static void SetSrcPage(pointer node);
  static void PushPage(pointer node);
  static void PopPageAndSwitchTo(pointer node);
  static void ResetTransitions(pointer node);
  static void SetPageTransition(pointer node, TransitionParam param);
};