package arkui.stateManagement.internal;

[Entity=Class]
interface PersistentStorageBackend {
    static (String or undefined) get(String key);
    static boolean has(String key);
    static void remove(String key);
    static void set(String key, String value);
    static void clear();
};

dictionary ColorMode {
    number LIGHT = 0;
    number DARK = 1;
};

dictionary LayoutDirection {
    number LTR = 0;
    number RTL = 1;
    [OriginalEnumMemberName=Auto]
    number AUTO = 2;
};

[Entity=Class]
interface EnvironmentBackend {
    static boolean isAccessibilityEnabled();
    static ColorMode getColorMode();
    static f32 getFontScale();
    static f32 getFontWeightScale();
    static LayoutDirection getLayoutDirection();
    static String getLanguageCode();
};
