package idlize.internal;

interface ESObject {};
interface Int8Array {};
interface Int16Array {};
interface Int32Array {};
interface Int64Array {};
interface Float32Array {};
interface Float64Array {};

interface DataView {};

namespace Intl {
    interface NumberFormat {};

    interface Locale {
        attribute String baseName;
        attribute String language;
        [Optional]
        attribute String calendar;
        [Optional]
        attribute String caseFirst;
        [Optional]
        attribute String collation;
        [Optional]
        attribute String hourCycle;
        [Optional]
        attribute String numberingSystem;
        [Optional]
        attribute boolean numeric;
        [Optional]
        attribute String region;
        [Optional]
        attribute String script;
    };
};

namespace jsonx {
    interface JsonElementSerializable {};
    interface JsonElementDeserializable {};
    interface JsonElement {};
};
