interface Int8Array {};
interface Int16Array {};
interface Int32Array {};
interface Int64Array {};
interface Float32Array {};
interface Float64Array {};

interface DataView {};

namespace Intl {
    interface NumberFormat {};
};

namespace jsonx {
    interface JsonElementSerializable {};
    interface JsonElementDeserializable {};
    interface JsonElement {};
};
