download koala_projects:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run download:koala_projects
  artifacts:
    paths:
    - external/koala_projects

<ArkTS> koala-projects integration test:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
    - download koala_projects
  before_script:
    - !reference [.npm, script]
    - npm i -C external/koala_projects --prefer-offline --no-audit --no-fund
    - npm run panda:sdk:install --prefix ./external/koala_projects/incremental/tools/panda
    - npm run sdk:all -C external/koala_projects
    - npm run build:all -C external/koala_projects/ui2abc
  script:
    # Bundle idlizer
    - npm run bundle:idlizer --prefix external/koala_projects/arkoala-arkts/tools/idlizer-bundler
    # Build
    - npm run build --prefix external/koala_projects/arkoala-arkts/arkui
    - npm run compile:native:node-host --prefix external/koala_projects/arkoala-arkts
    # Verify the outputs
    - ls -l external/koala_projects/arkoala-arkts/arkui/build/arkui.abc
    - ls -l external/koala_projects/arkoala-arkts/framework/native/build-node-host-vmloader/ArkoalaLoader.node
    - ls -l external/koala_projects/arkoala-arkts/framework/native/build-panda-host/libArkoalaNative_linux_x64_ani.so


arkgen ArkTS unit:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run -C arkgen/tests-template/arkts build
    - npm run -C arkgen/tests/unit init:arkts
    - npm run -C arkgen/tests/unit gen:arkts
    - npm run -C arkgen/tests/unit build:arkts
    - npm run -C arkgen/tests/unit build:arkts:native
    - npm run -C arkgen/tests/unit exec:arkts
  needs:
    - build idlize
    - download koala_projects

arkgen Kotlin unit:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - npm i -C external/koala_projects/tools --prefer-offline --no-audit --no-fund
  script:
    - npm run -C arkgen/tests/unit init:kt
    - npm run -C arkgen/tests/unit gen:kt
    - npm run -C arkgen/tests/unit build:kt:interop
    - npm run -C arkgen/tests/unit build:kt:native
    - npm run -C arkgen/tests/unit build:kt
    - npm run -C arkgen/tests/unit exec:kt
  needs:
    - build idlize
    - download koala_projects

arkgen golden unit CAPI:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run -C arkgen/tests/unit gen:golden
    - npm run -C arkgen/tests/unit exec:golden
  needs:
    - build idlize

pg cj:run:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - cd $CI_PROJECT_DIR/arkgen
  script:
    - LD_LIBRARY_PATH=LD_LIBRARY_PATH=$CANGJIE_HOME/runtime/lib/linux_x86_64_llvm:$CANGJIE_HOME/tools/lib:$LD_LIBRARY_PATH npm run all:subset:cj

arkgen Kotlin subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
    - download koala_projects
  before_script:
    - !reference [.npm, script]
    - npm i -C external/koala_projects/tools --prefer-offline --no-audit --no-fund
  script:
    - npm run -C arkgen setup:subset:kt
    - npm run -C arkgen gen:kt:subset
    - npm run -C arkgen compile:kt:interop
    - npm run -C arkgen compile:kt:native:subset
    - npm run -C arkgen compile:kt:subset
    - npm run -C arkgen exec:kt:subset

# Pack targets
pack idlize-arkgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: arkgen
  needs:
    - build idlize

pack idlize-core:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: core
  needs:
    - build idlize

pack idlize-linter:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: linter
  needs:
    - build idlize


# Publish targets
publish idlize-arkgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: arkgen
  needs:
    - build idlize

publish idlize-core:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: core
  needs:
    - build idlize

publish idlize-linter:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: linter
  needs:
    - build idlize
