arkgen TS subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    # - npm i --prefix external/incremental --prefer-offline --no-audit --no-fund
    # - npm i --prefix external/arkoala-arkts --prefer-offline --no-audit --no-fund
  script:
    - npm run -C arkgen setup:subset:ts
    - npm run -C arkgen gen-idl:subset:ts
    - npm run -C arkgen gen:subset:ts
    - npm run -C arkgen build:subset:ts
    - npm run -C arkgen build-native:subset:ts
    - npm run -C arkgen exec:subset:ts
  needs:
    - build idlize

arkgen ArkTS subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - npm run -C arkgen setup:subset:arkts
    - npm run -C arkgen gen-idl:subset:arkts
    - npm run -C arkgen gen:subset:arkts
    - npm run -C arkgen build:subset:arkts
    - npm run -C arkgen build-native:subset:arkts
    - npm run -C arkgen exec:subset:arkts
  needs:
    - build idlize
    - build external

arkgen ArkTS unit:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - npm run -C arkgen/tests/unit init:arkts
    - npm run -C arkgen/tests/unit gen:arkts
    - npm run -C arkgen/tests/unit build:arkts
    - npm run -C arkgen/tests/unit build:arkts:native
    - npm run -C arkgen/tests/unit exec:arkts
  needs:
    - build idlize
    - build external

arkgen Kotlin unit:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - npm run -C arkgen/tests/unit init:kt
    - npm run -C arkgen/tests/unit gen:kt
    - npm run -C arkgen/tests/unit build:kt:interop
    - npm run -C arkgen/tests/unit build:kt:native
    - npm run -C arkgen/tests/unit build:kt
    - npm run -C arkgen/tests/unit exec:kt
  needs:
    - build idlize
    - build external

pg cj:run:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - cd $CI_PROJECT_DIR/arkgen
  script:
    - LD_LIBRARY_PATH=LD_LIBRARY_PATH=$CANGJIE_HOME/runtime/lib/linux_x86_64_llvm:$CANGJIE_HOME/tools/lib:$LD_LIBRARY_PATH npm run all:subset:cj

arkgen Kotlin subset:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
  script:
    - npm run -C arkgen setup:subset:kt
    - npm run -C arkgen gen:kt:subset
    - npm run -C arkgen compile:kt:interop
    - npm run -C arkgen compile:kt:native:subset
    - npm run -C arkgen compile:kt:subset
    - npm run -C arkgen exec:kt:subset

arkgen TS sdk:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    # - npm i --prefix external/incremental --prefer-offline --no-audit --no-fund
    # - npm i --prefix external/arkoala-arkts --prefer-offline --no-audit --no-fund
  script:
    - npm run -C arkgen setup:sdk:ts
    - npm run -C arkgen gen-idl:sdk:ts
    - npm run -C arkgen gen:sdk:ts
    - npm run -C arkgen gen-modules:sdk:ts
    - npm run -C arkgen build:sdk:ts
    - npm run -C arkgen build-native:sdk:ts
    - npm run -C arkgen exec:sdk:ts
  needs:
    - build idlize
    - build external
    - download sdk

compile arkts peers:
  stage: test
  when: manual
  tags:
    - idlize-ci
    - koala-ci
  needs:
  - build idlize
  - build external
  - download sdk
  before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - cd $CI_PROJECT_DIR/arkgen
  script:
    - npm run make:compile:arkts:peers

build arkoala-ts:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - cd $CI_PROJECT_DIR/arkgen
  script:
    - npm run compile
    - KOALA_BZ=1 OPENLAB_USERNAME=koala-ci OPENLAB_PASSWORD=w1llUgu3ss npm run arkoala:ts

# Pack targets
pack idlize-arkgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: arkgen
  needs:
    - build idlize

pack idlize-core:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: core
  needs:
    - build idlize

pack idlize-linter:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: linter
  needs:
    - build idlize


# Publish targets
publish idlize-arkgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: arkgen
  needs:
    - build idlize

publish idlize-core:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: core
  needs:
    - build idlize

publish idlize-linter:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: linter
  needs:
    - build idlize


check index-full:
    stage: test
    tags:
      - idlize-ci
      - koala-ci
    needs:
    - build idlize
    - build external
    - download sdk
    before_script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - cd $CI_PROJECT_DIR/arkgen
    script:
      - npm run gen-idl:sdk:ts
      - npm run gen:sdk:ts
      - npm run check:index-full:ts

subset CAPI golden:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
    - cd $CI_PROJECT_DIR/arkgen
  script:
    - npm run test:subset-api
  needs:
    - build idlize