package "org.openharmony.idlize.predefined";

interface Loader {
    i32 LoadVirtualMachine(i32 arg0, String arg1, String arg2);
    i32 RunApplication(i32 arg0, i32 arg1);
    i32 StartApplication();
};
