package test_manually_decomposed_promise;

[Entity=Class]
interface FooResult {
    attribute number returnValue;
    attribute boolean state;
};

[Entity=Class]
interface FooWork {
    void Create();
    void Execute(number index, String name);
    FooResult Complete();
};
