/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package idlizer.runtime.native;

interface RawMemory {
    static RawMemory allocate();
    i32 getLength();
    void free();
};
interface SerializerBase {
    void writeUInt8(u8 val);
    void writeInt32(i32 val);
    void writeString(String val);
    void writePointer(pointer val);

    DeserializerBase swap();

    static SerializerBase use(RawMemory mem);
};
interface DeserializerBase {
    u8 readUInt8();
    i32 readInt32();
    String readString();
    pointer readPointer();

    SerializerBase swap();

    static DeserializerBase use(RawMemory mem);
};

///////////////////////////////////////////////////////

interface Event {
    attribute i32 eventKind;
    attribute i32 resourceId;
    attribute RawMemory memory;
};

Event poll();
