package "org.openharmony.idlize.predefined";

interface Interop {
    pointer GetGroupedLog(i32 index);
    void StartGroupedLog(i32 index);
    void StopGroupedLog(i32 index);
    void AppendGroupedLog(i32 index, String message);
    void PrintGroupedLog(i32 index);
    pointer GetStringFinalizer();
    void InvokeFinalizer(pointer ptr1, pointer ptr2);
    pointer GetPtrVectorElement(pointer ptr1, i32 arg);
    i32 StringLength(pointer ptr1);
    void StringData(pointer ptr1, sequence<u8> arr, i32 i);
    pointer StringMake(String str1);
    i32 GetPtrVectorSize(pointer ptr1);
    i32 ManagedStringWrite(String str1, sequence<u8> arr, i32 arg);
    void NativeLog(String str1);
    String Utf8ToString(sequence<u8> data, i32 offset, i32 length);
    String StdStringToString(pointer cstring);
    buffer MaterializeBuffer(pointer data, i32 length, i32 resourceId, pointer hold, pointer release);
    pointer GetNativeBufferPointer(buffer data);
    void CallCallback(i32 callbackKind, sequence<u8> args, i32 argsSize);
    void CallCallbackSync(i32 callbackKind, sequence<u8> args, i32 argsSize);
    void CallCallbackResourceHolder(pointer holder, i32 resourceId);
    void CallCallbackResourceReleaser(pointer releaser, i32 resourceId);
};
