package "org.openharmony.idlize.predefined";

interface Interop {
    void StartNativeTest(String ptr1, i32 arg);
    void StopNativeTest(i32 arg0);
    pointer GetGroupedLog(i32 arg0);
    void StartGroupedLog(i32 arg0);
    void StopGroupedLog(i32 arg0);
    pointer GetStringFinalizer();
    void InvokeFinalizer(pointer ptr1, pointer ptr2);
    pointer GetPtrVectorElement(pointer ptr1, i32 arg);
    pointer GetNodeFinalizer();
    i32 StringLength(pointer ptr1);
    void StringData(pointer ptr1, sequence<u8> arr, i32 i);
    pointer StringMake(String str1);
    i32 GetPtrVectorSize(pointer ptr1);
    i32 ManagedStringWrite(String str1, sequence<u8> arr, i32 arg);
    void Test_SetEventsApi();
    void Test_Common_OnChildTouchTest(sequence<u8> arr, i32 arg);
    void Test_List_OnScrollVisibleContentChange(sequence<u8> arr, i32 arg);
    void Test_TextPicker_OnAccept(sequence<u8> arr, i32 arg);
    i32 TestPerfNumber(i32 arg);
    void TestPerfNumberWithArray(sequence<u8> arr, i32 arg);
    void NativeLog(String str1);
    void StartPerf(String str1);
    void EndPerf(String str1);
    pointer DumpPerf(i32 arg);
    i32 CheckArkoalaGeneratedEvents(sequence<u8> result, i32 size);
    void CallCallback(i32 callbackKind, sequence<u8> args, i32 argsSize);
    void CallCallbackResourceHolder(pointer holder, i32 resourceId);
    void CallCallbackResourceReleaser(pointer releaser, i32 resourceId);
    i32 GetFrontCallback(sequence<u8> buffer, i32 bufferLength);
    i32 PopFrontCallback();
};
