package huks;

dictionary HuksTag {
    number HUKS_TAG_INVALID = 0;
    number HUKS_TAG_ALGORITHM = 536870913;
    number HUKS_TAG_PURPOSE = 536870914;
    number HUKS_TAG_KEY_SIZE = 536870915;
};

[Entity=Interface]
interface HuksParam {
    attribute HuksTag tag;
    attribute (boolean or number or buffer) value;
};

[Entity=Interface]
interface HuksOptions {
    [Optional]
    attribute sequence<HuksParam> properties;
    [Optional]
    attribute buffer inData;
};

[Entity=Interface]
interface HuksResult {
    attribute number errorCode;
    [Optional]
    attribute buffer outData;
    [Optional]
    attribute sequence<HuksParam> properties;
    [Optional]
    attribute sequence<String> certChains;
};

void fooVoidVoid();
void fooVoidNumber(number arg);
number fooNumberVoid();
number fooNumberNumber(number arg);
HuksResult fooResultNumber(number arg);
number fooNumberOptions(HuksOptions options);

HuksResult generateKeyItemSync(String keyAlias, HuksOptions options);
