package org.openharmony.idlize.predefined;

interface Test {
    i32 TestCallIntNoArgs(i32 arg0);
    i32 TestCallIntIntArraySum(i32 arg0, sequence<i32> arg1, i32 arg2);
    void TestCallVoidIntArrayPrefixSum(i32 arg0, sequence<i32> arr, i32 arg2);
    i32 TestCallIntRecursiveCallback(i32 arg0, sequence<u8> arr, i32 arg2);
    i32 TestCallIntMemory(i32 arg0, i32 arg1);
    void Test_SetEventsApi();
    void Test_Common_OnChildTouchTest(sequence<u8> arr, i32 arg);
    void Test_List_OnScrollVisibleContentChange(sequence<u8> arr, i32 arg);
    void Test_TextPicker_OnAccept(sequence<u8> arr, i32 arg);
    void TestWithBuffer(buffer buffer);
    void TestSetArkoalaCallbackCaller();
    void TestSetArkoalaCallbackCallerSync();
    pointer TestGetManagedCaller(i32 kind);
    pointer TestGetManagedCallerSync(i32 kind);
    pointer TestGetManagedHolder();
    pointer TestGetManagedReleaser();
    
    void TestReadAndMutateManagedBuffer(sequence<u8> arr, i32 len);
    // void TestCallbackSyncCall(sequence<u8> arr, i32 len);
};
