interface Error {};

[TypeParameters="T"]
interface AsyncCallback {};

typedef Object Any;

interface Function {};

interface ESObject {};

namespace jsonx {
    interface JsonElement {};
};

interface LocalStorage {};

interface DataView {};
