interface Error {};

[TypeParameters="T"]
interface AsyncCallback {};

typedef Any = Object;

interface Function {};

interface ESObject {};

namespace jsonx {
    interface JsonElement {};
};

interface LocalStorage {};

interface DataView {};

[TypeParameters="T"]
interface Partial {};
