interface Content {};
interface CustomTheme {};

interface NodeController {};
interface UIContext {};
interface GestureControl {};

interface RectShape {};
interface EllipseShape {};
interface CircleShape {};
interface PathShape {};

interface IntentionCode {};
interface DrawableDescriptor {};

interface Error {};
[TypeParameters="T"]
callback Function0 = void (T arg);
[TypeParameters="T"]
interface IterableIterator {};
[TypeParameters="T"]
interface ReadonlyArray {};

interface ParticleModifier {};
interface ParticleAttribute {};

interface LocalStorage {};

