interface CustomTheme {};

interface UIContext {};
interface GestureControl {};

interface RectShape {};
interface EllipseShape {};
interface CircleShape {};
interface PathShape {};

interface IntentionCode {};
interface DrawableDescriptor {};

interface Error {};

interface ParticleModifier {};
interface ParticleAttribute {};

interface LocalStorage {};
