package arkui.component.button;

enum ButtonType {
    [OriginalEnumMemberName=Capsule]
    number CAPSULE = 0;
    [OriginalEnumMemberName=Circle]
    number CIRCLE = 1;
    [OriginalEnumMemberName=Normal]
    number NORMAL = 2;
    number ROUNDED_RECTANGLE = 3;
};
[Entity=Interface]
interface ButtonOptions {
    [Optional]
    attribute ButtonType type;
};
[Entity=Interface]
interface ButtonInterface {
    [CallSignature]
    ButtonAttribute invoke(ResourceStr label, optional ButtonOptions options);
    [CallSignature]
    ButtonAttribute invoke(optional ButtonOptions options);
};
[Entity=Class, Component="Button"]
interface ButtonAttribute: [Extends, TypeArguments="ButtonAttribute"] CommonMethod {
    this type(ButtonType value);
};