package arkui.component.column;

[Entity=Class, Component="Column"]
interface ColumnAttribute: [Extends, TypeArguments="ColumnAttribute"] CommonMethod {
    this reverse(optional boolean isReversed);
};
