/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package arkui.component;

[Entity=Interface]
interface BaseEvent {
    attribute number timestamp;
    void test();
};
[Entity=Interface]
interface ClickEvent: BaseEvent {
    attribute number x;
    attribute number y;
};
[Synthetic]
callback Callback_ClickEvent_Void = void (ClickEvent event);
[Entity=Class, Component="CommonMethod"]
interface CommonMethod {
    constructor();
    this width(Length value);
    this height(Length value);
    this onClick(optional Callback_ClickEvent_Void event);
    this onClick(optional Callback_ClickEvent_Void event, optional f64 distanceThreshold);
};