/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package arkui.component.enums;

enum Color {
    [OriginalEnumMemberName=White]
    number WHITE = 0;
    [OriginalEnumMemberName=Black]
    number BLACK = 1;
    [OriginalEnumMemberName=Blue]
    number BLUE = 2;
    [OriginalEnumMemberName=Brown]
    number BROWN = 3;
    [OriginalEnumMemberName=Gray]
    number GRAY = 4;
    [OriginalEnumMemberName=Green]
    number GREEN = 5;
    [OriginalEnumMemberName=Grey]
    number GREY = 6;
    [OriginalEnumMemberName=Orange]
    number ORANGE = 7;
    [OriginalEnumMemberName=Pink]
    number PINK = 8;
    [OriginalEnumMemberName=Red]
    number RED = 9;
    [OriginalEnumMemberName=Yellow]
    number YELLOW = 10;
    [OriginalEnumMemberName=Transparent]
    number TRANSPARENT = 11;
};
