package arkui.component;

[Entity=Class]
interface DrawContext {
    void test();
};
[Synthetic]
callback Callback_DrawContext_Void = void (DrawContext drawContext);
[Entity=Class]
interface DrawModifier {
    [Optional]
    attribute Callback_DrawContext_Void drawBehind;
    void test();
};

dictionary ColorMode {
    number LIGHT = 0;
    number DARK = 1;
};

dictionary LayoutDirection {
    number LTR = 0;
    number RTL = 1;
    [OriginalEnumMemberName=Auto]
    number AUTO = 2;
};

[Entity=Class]
interface EventEmulator {
  static void emitClickEvent(pointer node, ClickEvent event);
  static void emitTextInputEvent(pointer node, String text);
};

[Component="Root"]
interface Root {};
