package arkui.component.idlize;

interface DrawContext {};
[Synthetic]
callback Callback_DrawContext_Void = void (DrawContext drawContext);
[Entity=Class]
interface DrawModifier {
    [Optional]
    attribute Callback_DrawContext_Void drawBehind;
    constructor();
};

[Component="Root"]
interface Root {};

[Component="ComponentRoot"]
interface ComponentRoot {};

[Component="RoutedPage"]
interface RoutedPage {};