package arkui.component;

interface Resource {
};

typedef (String or number or Resource) Length;
[Entity=Interface]
interface Position {
    [Optional]
    attribute Length x;
    [Optional]
    attribute Length y;
};