package arkui.component.units;

interface Resource {
};

typedef Length = (String or number or Resource);
[Entity=Interface]
interface Position {
    [Optional]
    attribute Length x;
    [Optional]
    attribute Length y;
};

typedef ResourceColor = (Color or number or String or Resource);
typedef ResourceStr = (String or Resource);

[Entity=Class]
interface ColorMetrics {
    constructor();
    static ColorMetrics numeric(number value);
    static ColorMetrics rgba(number red, number green, number blue, number alpha);
    static ColorMetrics resourceColor(ResourceColor color);
    ColorMetrics blendColor(ColorMetrics overlayColor);
    String color();
    number red();
    number green();
    number blue();
    number alpha();
};
