import { Finalizable } from "./Finalizable"
import { MaterializedBase } from "./MaterializedBase"
import { nativeModule } from "@koalaui/arkoala"
import { Serializer } from "./peers/Serializer"
import { isResource, isInstanceOf, runtimeType, RuntimeType, SerializerBase } from "./peers/SerializerBase"
import { unsafeCast } from "./shared/generated-utils"
import { registerCallback } from "./peers/SerializerBase"
import { wrapCallback } from "@koalaui/interop"
import { Deserializer, createDeserializer } from "./peers/Deserializer"
import { CallbackKind } from "./peers/CallbackKind"
import { CallbackTransformer } from "./peers/CallbackTransformer"