test arktscgen:
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - npm i --prefix external/incremental --prefer-offline --no-audit --no-fund
  script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - npm run all --prefix arktscgen
    - npm run build --prefix external/arkoala-arkts
    - npm run compile --prefix external/incremental/compat
    - npm run compile --prefix external/incremental/common
    - npm run compile --prefix external/incremental/harness
    - npm run build --prefix external/incremental/harness
    - npm run test --prefix external/ui2abc/libarkts
    - npm run test:all --prefix external/ui2abc/memo-plugin-ng

pack idlize-arktscgen:
  extends:
    - .npm-pack
  variables:
    PACKAGE_DIR: arktscgen
  needs:
    - build idlize

pre-publish test arktscgen:
  allow_failure: true
  stage: pre-publish
  needs:
  - build idlize
  tags:
    - idlize-ci
    - koala-ci
  script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - npm run test:pack --prefix arktscgen

publish idlize-arktscgen:
  extends:
    - .npm-publish
  variables:
    PACKAGE_DIR: arktscgen
  needs:
    - build idlize

