package ohos.font;

import global.resource.Resource as Resource;

namespace font {
    [Entity=Interface]
    interface UIFontFallbackInfo {
        attribute String language;
        attribute String family;
    };

    [Entity=Interface]
    interface UIFontAliasInfo {
        attribute String name;
        attribute number weight;
    };

    [Entity=Interface]
    interface UIFontAdjustInfo {
        attribute number weight;
        attribute number to;
    };

    [Entity=Interface]
    interface UIFontGenericInfo {
        attribute String family;
        attribute sequence<UIFontAliasInfo> alias;
        attribute sequence<UIFontAdjustInfo> adjust;
    };

    [Entity=Interface]
    interface UIFontFallbackGroupInfo {
        attribute String fontSetName;
        attribute sequence<UIFontFallbackInfo> fallback;
    };

    [Entity=Interface]
    interface UIFontConfig {
        attribute sequence<String> fontDir;
        attribute sequence<UIFontGenericInfo> generic;
        attribute sequence<UIFontFallbackGroupInfo> fallbackGroups;
    };

    UIFontConfig getUIFontConfig();
};

[Entity=Interface]
interface FontOptions {
    attribute (String or Resource) familyName;
    attribute (String or Resource) familySrc;
};

[Entity=Interface]
interface FontInfo {
    attribute String path;
    attribute String postScriptName;
    attribute String fullName;
    attribute String family;
    attribute String subfamily;
    attribute number weight;
    attribute number width;
    attribute boolean italic;
    attribute boolean monoSpace;
    attribute boolean symbolic;
};
