/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ohos.app.ability.common;

import application.BaseContext.BaseContext as BaseContext;

[Async]
callback Context_getGroupDir_Callback = void (String result);

[DefaultExport]
namespace common {
    [Entity=Class]
    interface Context: [Extends] BaseContext {
        // attribute resmgr.ResourceManager resourceManager;
        // attribute ApplicationInfo applicationInfo;
        attribute String cacheDir;
        attribute String tempDir;
        attribute String filesDir;
        attribute String databaseDir;
        attribute String preferencesDir;
        attribute String bundleCodeDir;
        attribute String distributedFilesDir;
        attribute String resourceDir;
        attribute String cloudFileDir;
        // attribute EventHub eventHub;
        // attribute contextConstant.AreaMode area;
        [Deprecated, Throws] Context createBundleContext(String bundleName);
        [Deprecated, Throws] Context createModuleContext(String moduleName);
        [Deprecated, Throws] Context createModuleContext(String bundleName, String moduleName);
        // [Throws] resmgr.ResourceManager createSystemHspModuleResourceManager(String bundleName, String moduleName);
        // [Throws] ApplicationContext getApplicationContext();
        [Throws] void getGroupDir(String dataGroupID, Context_getGroupDir_Callback callback_);
        [Throws] async String getGroupDir(String dataGroupID);
        // [Throws] resmgr.ResourceManager createModuleResourceManager(String bundleName, String moduleName);
    };
};
