/*
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ohos.window;

[DefaultExport]
namespace window {
    dictionary WindowStatusType {
        number UNDEFINED = 0;
        number FULL_SCREEN = 1;
        number MAXIMIZE = 2;
        number MINIMIZE = 3;
        number FLOATING = 4;
        number SPLIT_SCREEN = 5;
    };

    [Entity=Interface]
    interface SystemBarStyle {
        [Optional] attribute String statusBarContentColor;
    };

    dictionary Orientation {
        number UNSPECIFIED = 0;
    };
};