package ohos.arkui.shape;

import arkui.component.units;

[Entity=Class]
interface CircleShape {

    constructor(optional ShapeSize options);

    // the CommonShapeMethod part
    CircleShape offset(Position offset);
    CircleShape fill(ResourceColor color);
    CircleShape position(Position position);

    // the BaseShape part
    CircleShape width(Length width);
    CircleShape height(Length height);
    CircleShape size(SizeOptions size);
};

[Entity=Class]
interface EllipseShape {
    constructor(optional ShapeSize options);

    // the CommonShapeMethod part
    EllipseShape offset(Position offset);
    EllipseShape fill(ResourceColor color);
    EllipseShape position(Position position);

    // the BaseShape part
    EllipseShape width(Length width);
    EllipseShape height(Length height);
    EllipseShape size(SizeOptions size);
};

[Entity=Interface]
interface PathShapeOptions {
    [Optional]
    attribute String commands;
};

[Entity=Class]
interface PathShape {
    constructor(optional PathShapeOptions options);

    // the CommonShapeMethod part
    PathShape offset(Position offset);
    PathShape fill(ResourceColor color);
    PathShape position(Position position);

    PathShape commands(String commands);
};

[Entity=Interface]
interface ShapeSize {
    [Optional]
    attribute (number or String) width;
    [Optional]
    attribute (number or String) height;
};

[Entity=Interface]
interface RectShapeOptions: ShapeSize {
    [Optional]
    attribute (number or String or sequence<(number or String)>) radius;
};
[Entity=Interface]
interface RoundRectShapeOptions: ShapeSize {
    [Optional]
    attribute (number or String) radiusWidth;
    [Optional]
    attribute (number or String) radiusHeight;
};

interface RectShape {
    constructor(optional (RectShapeOptions or RoundRectShapeOptions) options);

    // the CommonShapeMethod part
    RectShape offset(Position offset);
    RectShape fill(ResourceColor color);
    RectShape position(Position position);

    // the BaseShape part
    RectShape width(Length width);
    RectShape height(Length height);
    RectShape size(SizeOptions size);

    RectShape radiusWidth((number or String) rWidth);
    RectShape radiusHeight((number or String) rHeight);
    RectShape radius((number or String or sequence<(number or String)>) radius);
};
