package ohos.promptAction;

dictionary LevelMode {
    number OVERLAY = 0;
    number EMBEDDED = 1;
};
dictionary ImmersiveMode {
    number DEFAULT = 0;
    number EXTEND = 1;
};

[Entity=Class]
interface LevelOrder {
    static LevelOrder clamp(number order);
    number getOrder();
};
[DefaultExport]
namespace promptAction {
    interface DialogController {};
};