package arkui.ComponentContent;

import arkui.Content.Content as Content;

[Entity=Class, Abstract]
interface ComponentContentBase: [Extends] Content {
    constructor();
};

[Entity=Class, TypeParameters="T", TypeParametersDefaults="undefined"]
interface ComponentContent: [Extends] ComponentContentBase {
    void update(Object args);
    void reuse(optional Object param);
    void recycle();
    void dispose();
    void updateConfiguration();
};