package arkui.FrameNode;

import arkui.component.units.Position as Position;
import ohos.arkui.UIContext.UIContext as UIContext;

[Entity=Class]
interface FrameNode {
    constructor(UIContext uiContext);
    // [Accessor=Getter]
    // readonly attribute UICommonEvent commonEvent;
    // [Accessor=Getter]
    // readonly attribute UIGestureEvent gestureEvent;
    // [Accessor=Getter]
    // readonly attribute CommonAttribute commonAttribute;
    // (RenderNode or undefined) getRenderNode();
    boolean isModifiable();
    void appendChild(FrameNode node);
    void insertChildAfter(FrameNode child, [Optional] FrameNode sibling);
    void removeChild(FrameNode node);
    void clearChildren();
    [Optional] FrameNode getChild(number index);
    [Optional] FrameNode getFirstChild();
    [Optional] FrameNode getNextSibling();
    [Optional] FrameNode getPreviousSibling();
    [Optional] FrameNode getParent();
    i32 getChildrenCount();
    void dispose();
    // Position getPositionToWindow();
    // Position getPositionToParent();
    // Size getMeasuredSize();
    // Position getLayoutPosition();
    // ([TypeArguments="LengthMetrics"] Edges) getUserConfigBorderWidth();
    // ([TypeArguments="LengthMetrics"] Edges) getUserConfigPadding();
    // ([TypeArguments="LengthMetrics"] Edges) getUserConfigMargin();
    // ([TypeArguments="LengthMetrics"] SizeT) getUserConfigSize();
    // String getId();
    // number getUniqueId();
    // String getNodeType();
    number getOpacity();
    // boolean isVisible();
    // boolean isClipToFrame();
    // boolean isAttached();
    // Object getInspectorInfo();
    // (Object or undefined) getCustomProperty(String name);
    // [Optional]
    // void onDraw(DrawContext context);
    // void onMeasure(LayoutConstraint constraint);
    // void onLayout(Position position);
    // void setMeasuredSize(Size size);
    // void setLayoutPosition(Position position);
    // void measure(LayoutConstraint constraint);
    // void layout(Position position);
    // void setNeedsLayout();
    // void invalidate();
    // Position getPositionToScreen();
    Position getPositionToWindowWithTransform();
    // Position getPositionToParentWithTransform();
    // Position getPositionToScreenWithTransform();
    // void disposeTree();
    // [TypeParameters="T"]
    // void addComponentContent([TypeArguments="T"] ComponentContent content);
    static FrameNode getFrameNodeByKey(String name);
};