package ohos.app.ability.Want;

[Entity=Class, DefaultExport]
interface Want {
    /**
     * bundle name
     */
    [Optional]
    attribute String bundleName;

    /**
     * ability name
     */
    [Optional]
    attribute String abilityName;

    /**
     * device id
     */
    [Optional]
    attribute String deviceId;

    /**
     * The description of a URI in a Want.
     */
    [Optional]
    attribute String uri;

    /**
     * The description of the type in this Want.
     */
    [Optional]
    attribute String type;

    /**
     * The options of the flags in this Want.
     */
    [Optional]
    attribute number flags;

    /**
     * The description of an action in an want.
     */
    [Optional]
    attribute String action;

    /**
     * The description of the WantParams object in an Want
     */
    [Optional]
    attribute record<String, Object> parameters;

    /**
     * The description of a entities in a Want.
     */
    [Optional]
    attribute sequence<String> entities;

    /**
     * The description of an module name in an want.
     */
    [Optional]
    attribute String moduleName;
};