package ohos.arkui.theme;
import arkui.component.units.ResourceColor as ResourceColor;
interface Theme {
    attribute Colors colors;
};
interface Colors {
    attribute ResourceColor brand;
    attribute ResourceColor warning;
    attribute ResourceColor alert;
    attribute ResourceColor confirm;
    attribute ResourceColor fontPrimary;
    attribute ResourceColor fontSecondary;
    attribute ResourceColor fontTertiary;
    attribute ResourceColor fontFourth;
    attribute ResourceColor fontEmphasize;
    attribute ResourceColor fontOnPrimary;
    attribute ResourceColor fontOnSecondary;
    attribute ResourceColor fontOnTertiary;
    attribute ResourceColor fontOnFourth;
    attribute ResourceColor iconPrimary;
    attribute ResourceColor iconSecondary;
    attribute ResourceColor iconTertiary;
    attribute ResourceColor iconFourth;
    attribute ResourceColor iconEmphasize;
    attribute ResourceColor iconSubEmphasize;
    attribute ResourceColor iconOnPrimary;
    attribute ResourceColor iconOnSecondary;
    attribute ResourceColor iconOnTertiary;
    attribute ResourceColor iconOnFourth;
    attribute ResourceColor backgroundPrimary;
    attribute ResourceColor backgroundSecondary;
    attribute ResourceColor backgroundTertiary;
    attribute ResourceColor backgroundFourth;
    attribute ResourceColor backgroundEmphasize;
    attribute ResourceColor compForegroundPrimary;
    attribute ResourceColor compBackgroundPrimary;
    attribute ResourceColor compBackgroundPrimaryTran;
    attribute ResourceColor compBackgroundPrimaryContrary;
    attribute ResourceColor compBackgroundGray;
    attribute ResourceColor compBackgroundSecondary;
    attribute ResourceColor compBackgroundTertiary;
    attribute ResourceColor compBackgroundEmphasize;
    attribute ResourceColor compBackgroundNeutral;
    attribute ResourceColor compEmphasizeSecondary;
    attribute ResourceColor compEmphasizeTertiary;
    attribute ResourceColor compDivider;
    attribute ResourceColor compCommonContrary;
    attribute ResourceColor compBackgroundFocus;
    attribute ResourceColor compFocusedPrimary;
    attribute ResourceColor compFocusedSecondary;
    attribute ResourceColor compFocusedTertiary;
    attribute ResourceColor interactiveHover;
    attribute ResourceColor interactivePressed;
    attribute ResourceColor interactiveFocus;
    attribute ResourceColor interactiveActive;
    attribute ResourceColor interactiveSelect;
    attribute ResourceColor interactiveClick;
};
interface CustomTheme {
    [Optional]
    attribute CustomColors colors;
};
typedef Colors CustomColors;
[Entity=Class]
interface ThemeControl {
    constructor();
    static void setDefaultTheme(CustomTheme theme);
};