package ohos.multimodalInput.intentionCode;
dictionary IntentionCode {
    number INTENTION_UNKNOWN = -1;
    number INTENTION_UP = 1;
    number INTENTION_DOWN = 2;
    number INTENTION_LEFT = 3;
    number INTENTION_RIGHT = 4;
    number INTENTION_SELECT = 5;
    number INTENTION_ESCAPE = 6;
    number INTENTION_BACK = 7;
    number INTENTION_FORWARD = 8;
    number INTENTION_MENU = 9;
    number INTENTION_PAGE_UP = 11;
    number INTENTION_PAGE_DOWN = 12;
    number INTENTION_ZOOM_OUT = 13;
    number INTENTION_ZOOM_IN = 14;
};