package deleted_declaration;
[Entity=Interface]
interface MyInterfaceToDelete {
};
[Entity=Class]
interface MyClassToDelete {
};
typedef MyTypedefToDelete = number;
void MyFunctionToDelete();
dictionary MyEnumToDelete {
    number VALUE = 0;
};