/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package method_literals;
[Entity=Interface]
interface Iface {
    [DtsName="foo", DtsTag="0|value|'my_literal'"]
    void fooMy_literal();
    [DtsName="boo", DtsTag="0|value1|'my_literal_1'"]
    void booMy_literal_1My_literal_2();
    [DtsName="goo", DtsTag="0|value1|'my_literal'"]
    void gooMy_literal(String value3);
    [DtsName="zoo", DtsTag="1|value1|'my_literal'"]
    void zooMy_literal(String value0, String value3);
};
[DtsName="foo", DtsTag="0|value|'my_literal'"]
void fooMy_literal();
[DtsName="boo", DtsTag="0|value1|'my_literal_1'"]
void booMy_literal_1My_literal_2();
[DtsName="goo", DtsTag="0|value1|'my_literal'"]
void gooMy_literal(String value3);
[DtsName="zoo", DtsTag="1|value2|'my_literal'"]
void zooMy_literal(String value1, String value3);