package primitives;
[Entity=Interface]
interface Iface {
    void foo(any value);
    this foo();
    void foo(Object value);
    void foo(number value);
    void foo(i32 value);
    void foo(f32 value);
    void foo(f64 value);
    void foo(boolean value);
    void foo(sequence<String> value);
    void foo(undefined value);
    void foo(record<String, number> value);
    void foo(date value);
    void foo(buffer value);
    void foo([TypeArguments="String"] Readonly value);
    void foo((String or undefined) value);
    any bar01();
    Object bar02();
    Object bar03();
    (String or undefined) bar04();
    String bar05();
    number bar06();
    i32 bar07();
    f32 bar08();
    long bar00();
    short bar10();
    void bar11();
    boolean bar12();
    char bar13();
    sequence<String> bar14();
    void bar15();
    date bar16();
    buffer bar17();
    String bar18();
    ([TypeArguments="String"] Readonly) bar19();
    (String or undefined) bar20();
};