package suggesting_names;
[Entity=Interface]
interface ShortValue {
};
[Entity=Interface]
interface VeryVeryLongValue1 {
};
[Entity=Interface]
interface VeryVeryLongValue2 {
};
[Entity=Interface]
interface VeryVeryLongValue3 {
};
[Entity=Interface]
interface VeryVeryLongValue4 {
};
[Entity=Interface]
interface VeryVeryLongValue5 {
};
[Entity=Interface]
interface VeryVeryLongValue6 {
};
[Entity=Interface]
interface VeryVeryLongValue7 {
};
[Synthetic]
callback Callback_ShortValue_Void = void (ShortValue value);
[Synthetic]
callback Callback_VeryVeryLongValue1_Void = void (VeryVeryLongValue1 value);
[Synthetic]
callback Callback_Union_VeryVeryLongValue1_VeryVeryLongValue2_Void = void ((VeryVeryLongValue1 or VeryVeryLongValue2) value);
[Synthetic]
callback Callback_Type_Iface_foo3_cb_value_Void = void ((VeryVeryLongValue1 or VeryVeryLongValue2 or VeryVeryLongValue3) value);
[Synthetic]
callback Callback_Type_Iface_foo4_cb_value_Void = void ((VeryVeryLongValue1 or VeryVeryLongValue2 or VeryVeryLongValue3 or VeryVeryLongValue4) value);
[Synthetic]
callback Callback_Type_Iface_foo5_cb_value_Void = void ((VeryVeryLongValue1 or VeryVeryLongValue2 or VeryVeryLongValue3 or VeryVeryLongValue4 or VeryVeryLongValue5) value);
[Synthetic]
callback Callback_Type_Iface_staticSuggestor_cb_value_Void = void ((VeryVeryLongValue1 or VeryVeryLongValue2 or VeryVeryLongValue3 or VeryVeryLongValue4 or VeryVeryLongValue5) value);
[Entity=Tuple, Synthetic]
interface Type_Iface_tupleSuggestor_value {
    attribute VeryVeryLongValue1 value0;
    attribute VeryVeryLongValue1 value1;
    attribute VeryVeryLongValue1 value2;
    attribute VeryVeryLongValue1 value3;
    attribute VeryVeryLongValue1 value4;
};
[Entity=Interface]
interface Iface {
    void foo6(Callback_ShortValue_Void cb);
    void foo1(Callback_VeryVeryLongValue1_Void cb);
    void foo2(Callback_Union_VeryVeryLongValue1_VeryVeryLongValue2_Void cb);
    void foo3(Callback_Type_Iface_foo3_cb_value_Void cb);
    void foo4(Callback_Type_Iface_foo4_cb_value_Void cb);
    void foo5(Callback_Type_Iface_foo5_cb_value_Void cb);
    static void staticSuggestor(Callback_Type_Iface_staticSuggestor_cb_value_Void cb);
    void tupleSuggestor(Type_Iface_tupleSuggestor_value value);
};