package idlize.internal;

interface Finalizable {};
interface SerializerBase {};
interface DeserializerBase {};
interface deserializeAndCallCallback {};
interface checkArkoalaCallbacks {};
interface CallbackTransformer {};
interface CallbackBuffer {};
interface CallbackResourceHolder {};
interface Tag {};
interface GENERATED_ArkUIEventsAPI {};
interface CallbackKind {};
interface KVMContext {};
interface TypeChecker {};
interface TSTypeChecker {};
interface ArkTSTypeChecker {};
