package idlize.stdlib;

[TSType=RuntimeType, CPPType=RuntimeType]
interface RuntimeType {};
[TSType=Materialized, CPPType=Materialized]
interface Materialized {};
[TSType=MaterializedBaseTag, CPPType=MaterializedBaseTag]
interface MaterializedBaseTag {};
[TSType=CallbackResource, CPPType=CallbackResource]
interface CallbackResource {};
[CPPType=VMContext]
interface VMContext {};
[TSType=Null]
interface Null {};
interface <T> Throws {
    attribute T value;
};

namespace Intl {
    interface Locale {};
};
interface Error {};
interface Type {};