package idlize.stdlib;

[TSType=RuntimeType, CPPType=RuntimeType]
interface RuntimeType {};
[TSType=Materialized, CPPType=Materialized]
interface Materialized {};
[TSType=CallbackResource, CPPType=CallbackResource]
interface CallbackResource {};
[CPPType=VMContext]
interface VMContext {};
