/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package idlize.typescript;

namespace Intl {
    interface Locale {};
};
interface Error {};
interface Type {};

typedef Int8Array = buffer;
typedef Int32Array = buffer;
typedef Int64Array = buffer;
typedef Uint8ClampedArray = buffer;
typedef Uint8Array = buffer;
typedef Uint32Array = buffer;
typedef Uint64Array = buffer;
typedef Float32Array = buffer;
typedef Float64Array = buffer;
typedef BigInt64Array = buffer;
typedef BigUint64Array = buffer;
typedef <T> FixedArray = buffer;
typedef <T> ReadonlyArray = buffer;
typedef DataView = buffer;
