/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ohos.base;
callback <T> Callback = void (T data);
[TypeParametersDefaults="BusinessError"]
callback <T> ErrorCallback = void (T err);
[TypeParametersDefaults="void"]
callback <T, E> AsyncCallback = void ((BusinessError<E> or idlize.stdlib.Null) err, (T or undefined) data);
[Entity=Class, TypeParametersDefaults="void"]
interface <T> BusinessError: [Extends] idlize.typescript.Error {
    constructor();
    constructor(i32 code, idlize.typescript.Error error);
    constructor(i32 code, T data, idlize.typescript.Error error);
    constructor(i32 code, String message, optional T data);
    // optional attribute (T or undefined) data;
};
typedef RecordData = ((idlize.stdlib.Null or Object) or undefined);