package org.openharmony.idlize.predefined;

callback Callback_Extender_OnProgress = void (f32 value);
callback Callback_Extender_OnFinish = void ();

[Entity=Interface]
interface DoubleAnimationParam {
    attribute String propertyName;
    attribute f32 startValue;
    attribute f32 endValue;
    attribute i32 duration;
    attribute i32 delay;
    attribute (Curve or String or ICurve) curve;

    [Optional]
    attribute Callback_Extender_OnProgress onProgress;

    [Optional]
    attribute Callback_Extender_OnFinish onFinish;
};

[Entity=Class]
interface AnimationExtender {
  static void SetClipRect(pointer node, f32 x, f32 y, f32 width, f32 height);
  static void OpenImplicitAnimation(AnimateParam param);
  static void CloseImplicitAnimation();
  static void StartDoubleAnimation(pointer node, DoubleAnimationParam param);
  static void AnimationTranslate(pointer node, TranslateOptions options);
};