
dictionary UniformDataType {

    String ENTITY = "general.entity";
    String OBJECT = "general.object";
    String COMPOSITE_OBJECT = "general.composite-object";
    String TEXT = "general.text";
    String PLAIN_TEXT = "general.plain-text";
    String HTML = "general.html";
    String HYPERLINK = "general.hyperlink";
    String XML = "general.xml";
    String XHTML = "general.xhtml";
    String RSS = "general.rss";
    String SMIL = "com.real.smil";
    String SOURCE_CODE = "general.source-code";
    String SCRIPT = "general.script";
    String SHELL_SCRIPT = "general.shell-script";
    String CSH_SCRIPT = "general.csh-script";
    String PERL_SCRIPT = "general.perl-script";
    String PHP_SCRIPT = "general.php-script";
    String PYTHON_SCRIPT = "general.python-script";
    String RUBY_SCRIPT = "general.ruby-script";
    String TYPE_SCRIPT = "general.type-script";
    String JAVA_SCRIPT = "general.java-script";
    String CSS = "general.css";
    String C_HEADER = "general.c-header";
    String C_SOURCE = "general.c-source";
    String C_PLUS_PLUS_HEADER = "general.c-plus-plus-header";
    String C_PLUS_PLUS_SOURCE = "general.c-plus-plus-source";
    String JAVA_SOURCE = "general.java-source";
    String TEX = "general.tex";
    String MARKDOWN = "general.markdown";
    String ASC_TEXT = "general.asc-text";
    String RICH_TEXT = "general.rich-text";
    String DELIMITED_VALUES_TEXT = "general.delimited-values-text";
    String COMMA_SEPARATED_VALUES_TEXT = "general.comma-separated-values-text";
    String TAB_SEPARATED_VALUES_TEXT = "general.tab-separated-values-text";
    String EBOOK = "general.ebook";
    String EPUB = "general.epub";
    String AZW = "com.amazon.azw";
    String AZW3 = "com.amazon.azw3";
    String KFX = "com.amazon.kfx";
    String MOBI = "com.amazon.mobi";
    String MEDIA = "general.media";
    String IMAGE = "general.image";
    String JPEG = "general.jpeg";
    String PNG = "general.png";
    String RAW_IMAGE = "general.raw-image";
    String TIFF = "general.tiff";
    String BMP = "com.microsoft.bmp";
    String ICO = "com.microsoft.ico";
    String PHOTOSHOP_IMAGE = "com.adobe.photoshop-image";
    String AI_IMAGE = "com.adobe.illustrator.ai-image";
    String FAX = "general.fax";
    String JFX_FAX = "com.j2.jfx-fax";
    String EFX_FAX = "com.js.efx-fax";
    String XBITMAP_IMAGE = "general.xbitmap-image";
    String GIF = "general.gif";
    String TGA_IMAGE = "com.truevision.tga-image";
    String SGI_IMAGE = "com.sgi.sgi-image";
    String OPENEXR_IMAGE = "com.ilm.openexr-image";
    String FLASHPIX_IMAGE = "com.kodak.flashpix.image";
    String WORD_DOC = "com.microsoft.word.doc";
    String EXCEL = "com.microsoft.excel.xls";
    String PPT = "com.microsoft.powerpoint.ppt";
    String WORD_DOT = "com.microsoft.word.dot";
    String POWERPOINT_PPS = "com.microsoft.powerpoint.pps";
    String POWERPOINT_POT = "com.microsoft.powerpoint.pot";
    String EXCEL_XLT = "com.microsoft.excel.xlt";
    String VISIO_VSD = "com.microsoft.visio.vsd";
    String PDF = "com.adobe.pdf";
    String POSTSCRIPT = "com.adobe.postscript";
    String ENCAPSULATED_POSTSCRIPT = "com.adobe.encapsulated-postscript";
    String VIDEO = "general.video";
    String AVI = "general.avi";
    String MPEG = "general.mpeg";
    String MPEG4 = "general.mpeg-4";
    String VIDEO_3GPP = "general.3gpp";
    String VIDEO_3GPP2 = "general.3gpp2";
    String TS = "general.ts";
    String MPEGURL_VIDEO = "general.mpegurl-video";
    String WINDOWS_MEDIA_WM = "com.microsoft.windows-media-wm";
    String WINDOWS_MEDIA_WMV = "com.microsoft.windows-media-wmv";
    String WINDOWS_MEDIA_WMP = "com.microsoft.windows-media-wmp";
    String WINDOWS_MEDIA_WVX = "com.microsoft.windows-media-wvx";
    String WINDOWS_MEDIA_WMX = "com.microsoft.windows-media-wmx";
    String REALMEDIA = "com.real.realmedia";
    String MATROSKA_VIDEO = "org.matroska.mkv";
    String FLASH = "com.adobe.flash";
    String AUDIO = "general.audio";
    String AAC = "general.aac";
    String AIFF = "general.aiff";
    String ALAC = "general.alac";
    String FLAC = "general.flac";
    String MP3 = "general.mp3";
    String OGG = "general.ogg";
    String PCM = "general.pcm";
    String WINDOWS_MEDIA_WMA = "com.microsoft.windows-media-wma";
    String WAVEFORM_AUDIO = "com.microsoft.waveform-audio";
    String WINDOWS_MEDIA_WAX = "com.microsoft.windows-media-wax";
    String AU_AUDIO = "general.au-audio";
    String AIFC_AUDIO = "general.aifc-audio";
    String MPEGURL_AUDIO = "general.mpegurl-audio";
    String MPEG_4_AUDIO = "general.mpeg-4-audio";
    String MP2 = "general.mp2";
    String MPEG_AUDIO = "general.mpeg-audio";
    String ULAW_AUDIO = "general.ulaw-audio";
    String SD2_AUDIO = "com.digidesign.sd2-audio";
    String REALAUDIO = "com.real.realaudio";
    String MATROSKA_AUDIO = "org.matroska.mka";
    String FILE = "general.file";
    String DIRECTORY = "general.directory";
    String FOLDER = "general.folder";
    String SYMLINK = "general.symlink";
    String ARCHIVE = "general.archive";
    String BZ2_ARCHIVE = "general.bz2-archive";
    String OPG = "general.opg";
    String TAZ_ARCHIVE = "general.taz-archive";
    String WEB_ARCHIVE = "general.web-archive";
    String DISK_IMAGE = "general.disk-image";
    String ISO = "general.iso";
    String TAR_ARCHIVE = "general.tar-archive";
    String ZIP_ARCHIVE = "general.zip-archive";
    String JAVA_ARCHIVE = "com.sun.java-archive";
    String GNU_TAR_ARCHIVE = "org.gnu.gnu-tar-archive";
    String GNU_ZIP_ARCHIVE = "org.gnu.gnu-zip-archive";
    String GNU_ZIP_TAR_ARCHIVE = "org.gnu.gnu-zip-tar-archive";
    String OPENXML = "org.openxmlformats.openxml";
    String WORDPROCESSINGML_DOCUMENT = "org.openxmlformats.wordprocessingml.document";
    String SPREADSHEETML_SHEET = "org.openxmlformats.spreadsheetml.sheet";
    String PRESENTATIONML_PRESENTATION = "org.openxmlformats.presentationml.presentation";
    String DRAWINGML_VISIO = "org.openxmlformats.drawingml.visio";
    String DRAWINGML_TEMPLATE = "org.openxmlformats.drawingml.template";
    String WORDPROCESSINGML_TEMPLATE = "org.openxmlformats.wordprocessingml.template";
    String PRESENTATIONML_TEMPLATE = "org.openxmlformats.presentationml.template";
    String PRESENTATIONML_SLIDESHOW = "org.openxmlformats.presentationml.slideshow";
    String SPREADSHEETML_TEMPLATE = "org.openxmlformats.spreadsheetml.template";
    String OPENDOCUMENT = "org.oasis.opendocument";
    String OPENDOCUMENT_TEXT = "org.oasis.opendocument.text";
    String OPENDOCUMENT_SPREADSHEET = "org.oasis.opendocument.spreadsheet";
    String OPENDOCUMENT_PRESENTATION = "org.oasis.opendocument.presentation";
    String OPENDOCUMENT_GRAPHICS = "org.oasis.opendocument.graphics";
    String OPENDOCUMENT_FORMULA = "org.oasis.opendocument.formula";
    String STUFFIT_ARCHIVE = "com.allume.stuffit-archive";
    String RAR_ARCHIVE = "com.rarlab.rar-archive";
    String SEVEN_ZIP_ARCHIVE = "org.7-zip.7-zip-archive";
    String CALENDAR = "general.calendar";
    String VCS = "general.vcs";
    String ICS = "general.ics";
    String CONTACT = "general.contact";
    String DATABASE = "general.database";
    String MESSAGE = "general.message";
    String EXECUTABLE = "general.executable";
    String PORTABLE_EXECUTABLE = "com.microsoft.portable-executable";
    String SUN_JAVA_CLASS = "com.sun.java-class";
    String VCARD = "general.vcard";
    String NAVIGATION = "general.navigation";
    String LOCATION = "general.location";
    String FONT = "general.font";
    String TRUETYPE_FONT = "general.truetype-font";
    String TRUETYPE_COLLECTION_FONT = "general.truetype-collection-font";
    String OPENTYPE_FONT = "general.opentype-font";
    String POSTSCRIPT_FONT = "com.adobe.postscript-font";
    String POSTSCRIPT_PFB_FONT = "com.adobe.postscript-pfb-font";
    String POSTSCRIPT_PFA_FONT = "com.adobe.postscript-pfa-font";
    String OPENHARMONY_FORM = "openharmony.form";
    String OPENHARMONY_APP_ITEM = "openharmony.app-item";
    String OPENHARMONY_PIXEL_MAP = "openharmony.pixel-map";
    String OPENHARMONY_ATOMIC_SERVICE = "openharmony.atomic-service";
    String OPENHARMONY_PACKAGE = "openharmony.package";
    String OPENHARMONY_HAP = "openharmony.hap";
    String OPENHARMONY_HDOC = "openharmony.hdoc";
    String OPENHARMONY_HINOTE = "openharmony.hinote";
    String OPENHARMONY_STYLED_STRING = "openharmony.styled-string";
    String OPENHARMONY_WANT = "openharmony.want";
    String OFD = "general.ofd";
    String CAD = "general.cad";
    String OCTET_STREAM = "general.octet-stream";

};
