package arkui.component.idlize;

import arkui.component.units;
import ohos.graphics.text.text;
import arkui.component.enums;
import ohos.multimedia.image.image;

[Entity=Interface]
interface WebHeader {
    attribute String headerKey;
    attribute String headerValue;
};

/**
 * The componentSnapshot API declaration , part for M2 app
 */
[Entity=Interface]
interface SnapshotOptions {
    [Optional]
    attribute number scale;
    [Optional]
    attribute boolean waitUntilRenderFinished;
};
[Async, Synthetic]
callback AsyncCallback_image_PixelMap_Void = void (PixelMap result);

[Entity=Class]
interface GlobalScope_ohos_arkui_componentSnapshot { // TODO WTF? Why GlobalScope in the name?
    static void get(String id, AsyncCallback_image_PixelMap_Void callback, optional SnapshotOptions options);
};

/**
 * The performanceMonitor API declaration, part for M2 app
 */
dictionary PerfMonitorActionType {

    number LAST_DOWN = 0;
    number LAST_UP = 1;
    number FIRST_MOVE = 2;

};
dictionary PerfMonitorSourceType {

    number PERF_TOUCH_EVENT = 0;
    number PERF_MOUSE_EVENT = 1;
    number PERF_TOUCHPAD_EVENT = 2;
    number PERF_JOYSTICK_EVENT = 3;
    number PERF_KEY_EVENT = 4;

};
[Entity=Class]
interface GlobalScope_ohos_arkui_performanceMonitor {
    static void begin(String scene, PerfMonitorActionType startInputType, optional String note);
    static void end(String scene);
    static void recordInputEventTime(PerfMonitorActionType actionType, PerfMonitorSourceType sourceType, i64 time);
};

/**
 * The common shapes API declarations
 */
[Entity=Class]
interface CommonShape {
    CommonShape offset(Position offset);
    CommonShape fill(ResourceColor color);
    CommonShape position(Position position);
};
[Entity=Class]
interface BaseShape {
    BaseShape width(Length width);
    BaseShape height(Length height);
    BaseShape size(SizeOptions size);
};

/**
 * The font API declaration, part for M2 app
 */
[Entity=Interface]
interface FontOptions {
    attribute (String or Resource) familyName;
    attribute (String or Resource) familySrc;
};

[Entity=Class]
interface GlobalScope_ohos_font {
    static void registerFont(FontOptions options);
    static sequence<String> getSystemFontList();
    static FontInfo getFontByName(String fontName);
};

/**
 * The MeasureUtils API declaration
 */
[Entity=Interface]
interface MeasureOptions {
    attribute (String or Resource) textContent;
    [Optional]
    attribute (number or String or Resource) constraintWidth;
    [Optional]
    attribute (number or String or Resource) fontSize;
    [Optional]
    attribute (number or FontStyle) fontStyle;
    [Optional]
    attribute (number or String or FontWeight) fontWeight;
    [Optional]
    attribute (String or Resource) fontFamily;
    [Optional]
    attribute (number or String) letterSpacing;
    [Optional]
    attribute (number or TextAlign) textAlign;
    [Optional]
    attribute (number or TextOverflow) overflow;
    [Optional]
    attribute number maxLines;
    [Optional]
    attribute (number or String or Resource) lineHeight;
    [Optional]
    attribute (number or String) baselineOffset;
    [Optional]
    attribute (number or TextCase) textCase;
    [Optional]
    attribute (number or String) textIndent;
    [Optional]
    attribute WordBreak wordBreak;
};

[Entity=Class]
interface GlobalScope_ohos_measure_utils {
    static number measureText(MeasureOptions options);
    static SizeOptions measureTextSize(MeasureOptions options);
};

/**
 * The SymbolEffect,ReplaceSymbolEffect,ScaleSymbolEffect API declaration, part for M2 app
 */

[Entity=Interface]
interface FontInfo {
    attribute String path;
    attribute String postScriptName;
    attribute String fullName;
    attribute String family;
    attribute String subfamily;
    attribute number weight;
    attribute number width;
    attribute boolean italic;
    attribute boolean monoSpace;
    attribute boolean symbolic;
};

[Entity=Interface]
interface IndicatorStyle {
    [Optional] attribute Length height;
    [Optional] attribute Length width;
    [Optional] attribute Length borderRadius;
    [Optional] attribute Length marginTop;
    [Optional] attribute ResourceColor color;
    [Optional, Deprecated] attribute ResourceColor selectedColor;
    [Optional, Deprecated] attribute Length left;
    [Optional, Deprecated] attribute Length top;
    [Optional, Deprecated] attribute Length right;
    [Optional, Deprecated] attribute Length bottom;
    [Optional, Deprecated] attribute Length size;
    [Optional, Deprecated] attribute boolean mask;
};
