package org.openharmony.arkui;

[/*Namespace=image,*/ Entity=Interface]
interface PixelMap {
    readonly attribute boolean isEditable;
    readonly attribute boolean isStrideAlignment;
    void readPixelsToBufferSync(buffer dst);
    void writeBufferToPixels(buffer src);
};