package org.openharmony.arkui;

[Entity=Tuple, Synthetic]
interface Tuple_Number_Number_Number {

    attribute number value0;
    attribute number value1;
    attribute number value2;

};

[Entity=Tuple, Synthetic]
interface Tuple_Number_Number {
    attribute number value0;
    attribute number value1;
};

