package arkui.component.idlize;

import ohos.graphics.common2D.common2D;
import ohos.graphics.drawing.drawing;

[Entity=Class]
interface DrawingColorFilter {
    static DrawingColorFilter createBlendModeColorFilter(Color color, BlendMode mode);
    static DrawingColorFilter createBlendModeColorFilter(number color, BlendMode mode);
    static DrawingColorFilter createComposeColorFilter(DrawingColorFilter outer, DrawingColorFilter inner);
    static DrawingColorFilter createLinearToSRGBGamma();
    static DrawingColorFilter createSRGBGammaToLinear();
    static DrawingColorFilter createLumaColorFilter();
    static DrawingColorFilter createMatrixColorFilter(sequence<number> matrix);
};

[Entity=Class]
interface DrawingLattice {
    static DrawingLattice createImageLattice(sequence<number> xDivs, sequence<number> yDivs, number fXCount, number fYCount, optional Rect fBounds, optional sequence<RectType> fRectTypes, optional sequence<(Color or number)> fColors);
};
