package arkui.component.idlize;

import arkui.component.builder;
import arkui.component.customDialogController;

[Entity=Interface]
interface CustomDialogBuildOptions {
    [Optional]
    attribute CustomDialogController controller;
};

[Entity=Interface]
interface CustomDialogControllerBuilder {
    attribute CustomDialogBuildOptions buildOptions;
    attribute CustomBuilder build;
};
