package org.openharmony.arkui;

dictionary TileMode {

    number CLAMP = 0;
    number REPEAT = 1;
    number MIRROR = 2;
    number DECAL = 3;

};
dictionary WaterRippleMode {

    number SMALL2MEDIUM_RECV = 0;
    number SMALL2MEDIUM_SEND = 1;
    number SMALL2SMALL = 2;

};
dictionary FlyMode {

    number BOTTOM = 0;
    number TOP = 1;

};

[Entity=Interface]
interface Filter {

    Filter pixelStretch(sequence<number> stretchSizes, TileMode tileMode);
    Filter blur(number blurRadius);
    Filter waterRipple(number progress, number waveCount, number x, number y, WaterRippleMode rippleMode);
    Filter flyInFlyOutEffect(number degree, FlyMode flyMode);
    Filter distort(number distortionK);

};

[Entity=Interface]
interface BrightnessBlender {

    attribute number cubicRate;
    attribute number quadraticRate;
    attribute number linearRate;
    attribute number degree;
    attribute number saturation;
    attribute Tuple_Number_Number_Number positiveCoefficient;
    attribute Tuple_Number_Number_Number negativeCoefficient;
    attribute number fraction;

};

typedef BrightnessBlender Blender;

[Entity=Interface]
interface VisualEffect {

    VisualEffect backgroundColorBlender(BrightnessBlender blender);

};
