    [Entity=Interface]
    interface DateTimeOptions {

        [Optional]
        attribute String locale;
        [Optional]
        attribute String dateStyle;
        [Optional]
        attribute String timeStyle;
        [Optional]
        attribute String hourCycle;
        [Optional]
        attribute String timeZone;
        [Optional]
        attribute String numberingSystem;
        [Optional]
        attribute boolean hour12;
        [Optional]
        attribute String weekday;
        [Optional]
        attribute String era;
        [Optional]
        attribute String year;
        [Optional]
        attribute String month;
        [Optional]
        attribute String day;
        [Optional]
        attribute String hour;
        [Optional]
        attribute String minute;
        [Optional]
        attribute String second;
        [Optional]
        attribute String timeZoneName;
        [Optional]
        attribute String dayPeriod;
        [Optional]
        attribute String localeMatcher;
        [Optional]
        attribute String formatMatcher;

    };