package api.internal.component.ets;


/**
 * Defines Text Modifier
 */
[Entity=Class, Interfaces="AttributeModifier", ParentTypeArguments="<object>"]
interface TextModifier {};

/*[Namespace=text]*/
dictionary RectWidthStyle {
    number TIGHT = 0;
    number MAX = 1;
};

/*[Namespace=text]*/
dictionary RectHeightStyle {
    number TIGHT = 0;
    number MAX = 1;
    number INCLUDE_LINE_SPACE_MIDDLE = 2;
    number INCLUDE_LINE_SPACE_TOP = 3;
    number INCLUDE_LINE_SPACE_BOTTOM = 4;
    number STRUT = 5;
};

/**
 * The ColorMetrics API declaration, part for M2 app
 */
[Entity=Class]
interface ColorMetrics {
    [Accessor=Getter]
    readonly attribute String color;
    [Accessor=Getter]
    readonly attribute number red;
    [Accessor=Getter]
    readonly attribute number green;
    [Accessor=Getter]
    readonly attribute number blue;
    [Accessor=Getter]
    readonly attribute number alpha;
    static ColorMetrics numeric(number value);
    static ColorMetrics rgba(number red, number green, number blue, optional number alpha);
    static ColorMetrics resourceColor(ResourceColor color);
    ColorMetrics blendColor(ColorMetrics overlayColor);
};

[Entity=Interface]
interface WebHeader {
    attribute String headerKey;
    attribute String headerValue;
};

[Entity=Class]
interface WebviewController {
  static void initializeWebEngine();
  void loadUrl((String or Resource) url, optional sequence<WebHeader> headers);
};

/**
 * The componentSnapshot API declaration , part for M2 app
 */
[Entity=Interface]
interface SnapshotOptions {
    [Optional]
    attribute number scale;
    [Optional]
    attribute boolean waitUntilRenderFinished;
};
[Async, Synthetic]
callback AsyncCallback_image_PixelMap_Void = void (PixelMap result);

[Entity=Class]
interface GlobalScope_ohos_arkui_componentSnapshot {
    static void get(String id, AsyncCallback_image_PixelMap_Void callback, optional SnapshotOptions options);
};

/**
 * The performanceMonitor API declaration, part for M2 app
 */
dictionary PerfMonitorActionType {

    number LAST_DOWN = 0;
    number LAST_UP = 1;
    number FIRST_MOVE = 2;

};
dictionary PerfMonitorSourceType {

    number PERF_TOUCH_EVENT = 0;
    number PERF_MOUSE_EVENT = 1;
    number PERF_TOUCHPAD_EVENT = 2;
    number PERF_JOYSTICK_EVENT = 3;
    number PERF_KEY_EVENT = 4;

};
[Entity=Class]
interface GlobalScope_ohos_arkui_performanceMonitor {
    static void begin(String scene, PerfMonitorActionType startInputType, optional String note);
    static void end(String scene);
    static void recordInputEventTime(PerfMonitorActionType actionType, PerfMonitorSourceType sourceType, i64 time);
};

/**
 * The common shapes API declarations
 */
[Entity=Class]
interface CommonShape {
    CommonShape offset(Position offset);
    CommonShape fill(ResourceColor color);
    CommonShape position(Position position);
};
[Entity=Class]
interface BaseShape {
    BaseShape width(Length width);
    BaseShape height(Length height);
    BaseShape size(SizeOptions size);
};

/**
 * The RectShape declaration
 */
[Entity=Interface]
interface ShapeSize {
    [Optional]
    attribute (number or String) width;
    [Optional]
    attribute (number or String) height;
};
[Entity=Interface]
interface RectShapeOptions: ShapeSize {
    [Optional]
    attribute (number or String or sequence<(number or String)>) radius;
};
[Entity=Interface]
interface RoundRectShapeOptions: ShapeSize {
    [Optional]
    attribute (number or String) radiusWidth;
    [Optional]
    attribute (number or String) radiusHeight;
};

[Entity=Class]
interface RectShape {
    constructor(optional (RectShapeOptions or RoundRectShapeOptions) options);

    // the CommonShapeMethod part
    RectShape offset(Position offset);
    RectShape fill(ResourceColor color);
    RectShape position(Position position);

    // the BaseShape part
    RectShape width(Length width);
    RectShape height(Length height);
    RectShape size(SizeOptions size);

    RectShape radiusWidth((number or String) rWidth);
    RectShape radiusHeight((number or String) rHeight);
    RectShape radius((number or String or sequence<(number or String)>) radius);
};

/**
 *  The CircleShape declaration
 */
[Entity=Class]
interface CircleShape {

    constructor(optional ShapeSize options);

    // the CommonShapeMethod part
    CircleShape offset(Position offset);
    CircleShape fill(ResourceColor color);
    CircleShape position(Position position);

    // the BaseShape part
    CircleShape width(Length width);
    CircleShape height(Length height);
    CircleShape size(SizeOptions size);
};

/**
 *  The EllipseShape declaration
 */
[Entity=Class]
interface EllipseShape {
    constructor(optional ShapeSize options);

    // the CommonShapeMethod part
    EllipseShape offset(Position offset);
    EllipseShape fill(ResourceColor color);
    EllipseShape position(Position position);

    // the BaseShape part
    EllipseShape width(Length width);
    EllipseShape height(Length height);
    EllipseShape size(SizeOptions size);
};

/**
 *  The PathShape declaration
 */
[Entity=Interface]
interface PathShapeOptions {
    [Optional]
    attribute String commands;
};

[Entity=Class]
interface PathShape {
    constructor(optional PathShapeOptions options);

    // the CommonShapeMethod part
    PathShape offset(Position offset);
    PathShape fill(ResourceColor color);
    PathShape position(Position position);

    PathShape commands(String commands);
};

/**
 * The font API declaration, part for M2 app
 */
[Entity=Interface]
interface FontOptions {
    attribute (String or Resource) familyName;
    attribute (String or Resource) familySrc;
};

[Entity=Interface]
interface FontInfo {
    attribute String path;
    attribute String postScriptName;
    attribute String fullName;
    attribute String family;
    attribute String subfamily;
    attribute number weight;
    attribute number width;
    attribute boolean italic;
    attribute boolean monoSpace;
    attribute boolean symbolic;
};

[Entity=Class]
interface GlobalScope_ohos_font {
    static void registerFont(FontOptions options);
    static sequence<String> getSystemFontList();
    static FontInfo getFontByName(String fontName);
};

/**
 * The MeasureUtils API declaration
 */
[Entity=Interface]
interface MeasureOptions {
    attribute (String or Resource) textContent;
    [Optional]
    attribute (number or String or Resource) constraintWidth;
    [Optional]
    attribute (number or String or Resource) fontSize;
    [Optional]
    attribute (number or FontStyle) fontStyle;
    [Optional]
    attribute (number or String or FontWeight) fontWeight;
    [Optional]
    attribute (String or Resource) fontFamily;
    [Optional]
    attribute (number or String) letterSpacing;
    [Optional]
    attribute (number or TextAlign) textAlign;
    [Optional]
    attribute (number or TextOverflow) overflow;
    [Optional]
    attribute number maxLines;
    [Optional]
    attribute (number or String or Resource) lineHeight;
    [Optional]
    attribute (number or String) baselineOffset;
    [Optional]
    attribute (number or TextCase) textCase;
    [Optional]
    attribute (number or String) textIndent;
    [Optional]
    attribute WordBreak wordBreak;
};

[Entity=Class]
interface GlobalScope_ohos_measure_utils {
    static number measureText(MeasureOptions options);
    static SizeOptions measureTextSize(MeasureOptions options);
};

/**
 * The SymbolEffect,ReplaceSymbolEffect,ScaleSymbolEffect API declaration, part for M2 app
 */
dictionary EffectDirection {
    number DOWN = 0;
    number UP = 1;
};

dictionary EffectScope {
    number LAYER = 0;
    number WHOLE = 1;
};

[Entity=Class]
interface SymbolEffect {
    void dummyForAccessorGenerate();
};

[Entity=Class]
interface ScaleSymbolEffect: SymbolEffect {
    constructor(optional EffectScope scope, optional EffectDirection direction);
    [Optional]
    attribute EffectScope scope;
    [Optional]
    attribute EffectDirection direction;
};

[Entity=Class]
interface ReplaceSymbolEffect: SymbolEffect {
    constructor(optional EffectScope scope);
    [Optional]
    attribute EffectScope scope;
};

[Entity=Interface]
interface FontInfo {
    attribute String path;
    attribute String postScriptName;
    attribute String fullName;
    attribute String family;
    attribute String subfamily;
    attribute number weight;
    attribute number width;
    attribute boolean italic;
    attribute boolean monoSpace;
    attribute boolean symbolic;
};

[Entity=Interface]
interface TouchPoint {

    attribute Dimension x;
    attribute Dimension y;

};

/*
* from @ohos.deviceStatus.dragInteraction.idl
*/
[Entity=Interface]
interface Summary {

    attribute String dataType;
    attribute number dataSize;

};

/*
* from ui_extension_component.idl
*/
callback ReceiveCallback = void (record<String, Object> data);

/*
* from @ohos.multimedia.image.idl
*/
dictionary ResolutionQuality {

    number LOW = 1;
    number MEDIUM = 2;
    number HIGH = 3;

};

/*
* from image.idl
*/
typedef Matrix4Transit ImageMatrix;

/*
* from @ohos.multimodalInput.intentionCode.idl
*/
dictionary IntentionCode {
    number INTENTION_UNKNOWN = -1;
    number INTENTION_UP = 1;
    number INTENTION_DOWN = 2;
    number INTENTION_LEFT = 3;
    number INTENTION_RIGHT = 4;
    number INTENTION_SELECT = 5;
    number INTENTION_ESCAPE = 6;
    number INTENTION_BACK = 7;
    number INTENTION_FORWARD = 8;
    number INTENTION_MENU = 9;
    number INTENTION_PAGE_UP = 11;
    number INTENTION_PAGE_DOWN = 12;
    number INTENTION_ZOOM_OUT = 13;
    number INTENTION_ZOOM_IN = 14;
};

/*
* from @ohos.window.idl
*/
dictionary WindowStatusType {
    number UNDEFINED = 0;
    number FULL_SCREEN = 1;
    number MAXIMIZE = 2;
    number MINIMIZE = 3;
    number FLOATING = 4;
    number SPLIT_SCREEN = 5;
};