package arkui.component.idlize;

callback NavExtender_OnUpdateStack = void ();

[Entity=Class]
interface NavExtender {
  static void setNavigationOptions(pointer ptr, NavPathStack pathStack);
  static void setUpdateStackCallback(NavPathStack peer, NavExtender_OnUpdateStack callback);
  static void syncStack(NavPathStack peer);
  static boolean checkNeedCreate(pointer navigation, i32 index);
  static void setNavDestinationNode(NavPathStack peer, i32 index, pointer node);
  static void pushPath(NavPathStack pathStack, NavPathInfo info, NavigationOptions options);
  static void replacePath(NavPathStack pathStack, NavPathInfo info, NavigationOptions options);
  static String pop(NavPathStack pathStack, boolean animated);
  static void setOnPopCallback(NavPathStack pathStack, Callback_String_Void popCallback);
  static String getIdByIndex(NavPathStack pathStack, i32 index);
  static sequence<String> getIdByName(NavPathStack pathStack, String name);
  static void popToIndex(NavPathStack pathStack, i32 index, boolean animated);
  static number popToName(NavPathStack pathStack, String name, boolean animated);
};
