package api.global;

interface Resource {
  attribute String bundleName;
  attribute String moduleName;
  attribute number id;
  [Optional]
  attribute sequence<String> params;
  [Optional]
  attribute number type;
};