package arkui.component.idlize;

[Component="Root"]
interface Root {};

[Component="ComponentRoot"]
interface ComponentRoot {};

callback Callback_onMeasureSize_SizeResult = SizeResult (GeometryInfo selfLayoutInfo, sequence<Measurable> children, ConstraintSizeOptions constraint);
callback Callback_onPlaceChildren_Void = void (GeometryInfo selfLayoutInfo, sequence<Layoutable> children, ConstraintSizeOptions constraint);

[Component="CustomLayoutRoot"]
interface CustomLayoutRoot {
    [CommonMethod]
    attribute Callback_onMeasureSize_SizeResult subscribeOnMeasureSize;
    [CommonMethod]
    attribute Callback_onPlaceChildren_Void subscribeOnPlaceChildren;
};