package main;

import deps.Size as IntSize;

interface Size {
    attribute number numHeight;
    attribute number numWidth;
};

interface Sizes {
    attribute Size numSize;
    attribute IntSize intSize;
    attribute deps.fp.Size floatSize;
};

void resize(Sizes sizes);
void resize3(Size numSize, IntSize intSize, deps.fp.Size floatSize);
