/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ost.unions;

import ost.enums.PlainEnum;
import ost.generics.GenericBox;

interface UnionInterface {
    attribute (String or PlainEnum or sequence<boolean> or sequence<PlainEnum>) prop;
};

// return selector value (0 for first union component, 1 for second etc)
i32 checkUnionInterface(UnionInterface arg);
i32 checkUnionArg((String or PlainEnum or sequence<boolean> or sequence<PlainEnum>) arg);
i32 checkGenericUnion((String or GenericBox<String> or GenericBox<UnionInterface>) arg);
