/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ost.enums;

enum PlainEnum {
    number E1;
    number E2;
    number E3;
};

enum IntEnum {
    i32 E1 = 1;
    i32 E3 = 3;
};

enum LongEnum {
    number POS = 0x80000000;
    number NEG = -0x80000001;
};

enum LegacyEnum {
    number FIRST = 0;
    [OriginalEnumMemberName=first]
    number LEGACY_FIRST = 0;
    number SECOND = 1;
    [OriginalEnumMemberName=second]
    number LEGACY_SECOND = 1;
    number THIRD = 2;
    [OriginalEnumMemberName=third]
    number LEGACY_THIRD = 2;
};

enum StringEnum {
    String S1 = "one";
    String S2 = "two";
};

PlainEnum checkPlainEnum(PlainEnum enumValue, i32 step);
IntEnum checkIntEnum(IntEnum enumValue, i32 value);
LongEnum checkLongEnum(LongEnum enumValue);
LegacyEnum checkLegacyEnum(LegacyEnum enumValue, i32 value);
StringEnum checkStringEnum(StringEnum enumValue, String value);
