/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ost.overrides;

[Entity=Class]
interface MultiCtor {
    attribute String name;
    attribute i32 age;
    constructor(String name);
    constructor(i32 age);
    constructor(String name, i32 age);
};

interface MultiMethod {
    number valueOf(i32 n);            // == n
    number valueOf(String s);         // == s.length
    number valueOf(i32 n, String s);  // == n + s.length
};
