/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ost.dataclasses;

// Checks that class values are initialized properly
[Entity=Tuple, Synthetic]
interface Tuple_Boolean_Number_String {
    attribute boolean value0;
    attribute number value1;
    attribute String value2;
};

interface MyObject {
    attribute boolean booleanValue;
    attribute number numberValue;
    attribute String stringValue;
};

interface DataInterface {
    attribute boolean booleanProp;
    attribute number numericProp;
    attribute String stringProp;
    attribute MyObject objectProp;
    attribute Tuple_Boolean_Number_String tupleProp;
};

[Entity=Class]
interface DataClass: DataInterface {
    attribute boolean booleanProp;
    attribute number numericProp;
    attribute String stringProp;
    attribute MyObject objectProp;
    attribute Tuple_Boolean_Number_String tupleProp;
};
