check arkui interfaces:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
    - koala-ci
  needs:
    - build idlize
    - download sdk
    - build external
  script:
    - !reference [.npm, script]
    - !reference [.panda, script]
    - npm run -C etsgen run:sdk
    - node idlinter --check interfaces/interfaces etsgen/out
