export class MediaQuery {}
export class UIInspector {}
export class Router {}
export interface TargetInfo {}
export class PromptAction {}
export interface PageInfo {}
export interface OverlayManagerOptions {}
export class UIObserver {}
export class OverlayManager {}
export class UIContext {}
