[Entity=Class]
interface WithMethods {
    [Optional]
    optional attribute number returnValue;
    void Method1(number arg);
    number Method2();
};
interface DataClass: [Extends] WithMethods {
    void Method3(String s);
};