package arkui.AttributeUpdater;
import ohos.arkui.component.AttributeModifier as AttributeModifier;

// Improve: used in conf/ets-sdk.refs.json
[Entity=Class]
interface <T> AttributeUpdater: AttributeModifier<T> {
    constructor();
};