package demo.test.methods;

interface Vec2 {
    attribute i32 x;
    attribute i32 y;
};

interface Vec3 {
    attribute i32 x;
    attribute i32 y;
    attribute i32 z;
};

interface NamedDot {
    attribute Vec3 position;
    attribute String name;
};

interface NameDotSpace {
    [Name="NameDotSpacePush"]
    void push(NamedDot dot);
    [Name="NameDotSpacePrint"]
    void print();
    [Name="NameDotSpaceGenNewPosition"]
    static Vec3 genNewPosition(i32 seed);
    [Name="NameDotSpaceAdd3"]
    static Vec3 add3(Vec3 a, Vec3 b);
};
