package arkui.component.check.modifiers;

[Component]
interface CheckCustomModifierAttribute: Root {
    attribute number prop;
};

[Component]
interface CheckTrivialModifierAttribute: Root {
    attribute number prop;
};

[Component]
interface CheckNoModifiersAttribute: Root {
    attribute number prop;
};
