/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package arkui.component.check.extendable;

import arkui.component.builder.ConstructorT as ConstructorT;
import arkui.component.builder.CustomBuilder as CustomBuilder;
import arkui.component.builder.CustomBuilderT as CustomBuilderT;

interface CheckExtendableOptions {
    [Optional]
    attribute i32 intAttr;
};

[Component]
interface CheckExtendableAttribute: Root {
    this commonMethodBoolean(boolean flag);
    [CommonMethod]
    attribute (i32 or undefined) fontSize;
};

[ComponentInterface]
interface CheckExtendableInterface {
    [CallSignature]
    CheckExtendableAttribute invoke(optional CheckExtendableOptions options, optional CustomBuilder content_);
};

[Entity=Class, Abstract]
interface ExtendableCheckExtendable: CheckExtendableAttribute {
    constructor();
    static <T> T $_instantiate(ConstructorT<T> factory, optional CheckExtendableOptions options, optional CustomBuilder content_);
    [TypeAnnotations=Builder]
    static <T> void _instantiateImpl(CustomBuilderT<T> styles, ConstructorT<T> factory, optional CustomBuilder content_);
};

[Component]
interface CheckExtendableNoContentAttribute: Root {
    this commonMethodBoolean(boolean flag);
};

[ComponentInterface]
interface CheckExtendableNoContentInterface {
    [CallSignature]
    CheckExtendableAttribute invoke(optional CheckExtendableOptions options);
};

[Entity=Class, Abstract]
interface ExtendableCheckExtendableNoContent: CheckExtendableNoContentAttribute {
    constructor();
    static <T> T $_instantiate(ConstructorT<T> factory, optional CheckExtendableOptions options);
    [TypeAnnotations=Builder]
    static <T> void _instantiateImpl(CustomBuilderT<T> styles, ConstructorT<T> factory);
    this setCheckExtendableNoContentOptions(optional CheckExtendableOptions options);
};
