package arkui.component.check.enum;

dictionary EnumUByte {
    number E0 = 0;
    number E1 = 1;
    number E255 = 255;
};

dictionary EnumByte {
    number E0 = 0;
    number EN127 = -127;
    number E127 = 127;
};

dictionary EnumInt {
    number E0 = 0;
    number E512 = 512;
};

dictionary EnumLong {
    number E0 = 0;
    number EFFFFFFFFA = 0xFFFFFFFFA;
};

[Component]
interface CheckEnumAttribute: Root {

    attribute EnumUByte enumUByte;
    attribute EnumByte enumByte;
    attribute EnumInt enumInt;
    attribute EnumLong enumLong;
};
