package arkui.component.check.hierarchy;

[Component]
interface CheckParentAttribute: Root {
    this commonMethodBoolean(boolean flag);
};

[Component]
interface CheckChildAttribute: CheckParentAttribute {
    this commonMethodBoolean(boolean flag);
};
