/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package arkui.component.check.duplicates;

interface DuplicateInteraceParent {
    attribute boolean parentEnabled;
    attribute boolean commonEnabled;
};

interface DuplicateInteraceChild: DuplicateInteraceParent{
    attribute boolean childEnabled;
    attribute boolean commonEnabled;
};

interface DuplicateInteraceSubChild: DuplicateInteraceChild{
    attribute boolean subChildEnabled;
    attribute boolean commonEnabled;
};

[Component]
interface CheckDuplicateParentAttribute: Root {
    attribute DuplicateInteraceParent parentDuplicateInterface;
    attribute DuplicateInteraceChild commonProperty;
    attribute DuplicateInteraceSubChild subChildDuplicateInterface;
    this commonMethod((DuplicateInteraceParent or undefined) param1, optional DuplicateInteraceSubChild param2);
};

[Component]
interface CheckDuplicateChildAttribute: CheckDuplicateParentAttribute {
    attribute DuplicateInteraceChild commonProperty;
    this commonMethod((DuplicateInteraceParent or undefined) param1, optional (DuplicateInteraceSubChild or undefined) param2);
};

[Entity=Class]
interface DuplicateClassParent {
    attribute boolean parentEnabled;
    attribute boolean commonEnabled;
    static attribute boolean parentStatic;
};

[Entity=Class]
interface DuplicateClassChild: DuplicateClassParent {
    attribute boolean childEnabled;
    attribute boolean commonEnabled;
    static attribute boolean parentStatic;
    static attribute boolean childStatic;
};
