/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package arkui.component.common;
import arkui.component.units.Length as Length;
import arkui.Graphics.DrawContext as _DrawContext;
import arkui.CheckCustomModifierModifier.CheckCustomModifierModifier as CheckCustomModifierModifier;
import arkui.CheckTrivialModifierModifier.CheckTrivialModifierModifier as CheckTrivialModifierModifier;
typedef DrawContext = _DrawContext;

// Improve: used in conf/ets-sdk.refs.json
interface <T> AttributeModifier {
    void applyNormalAttribute(T instance);
};

interface BaseEvent {
    attribute number timestamp;
};

// Improve: required for CallDrawModifierCallbacks in dummy_impl.cpp
[Synthetic]
callback Callback_Void = void ();
interface ClickEvent: BaseEvent {
    attribute number x;
    attribute number y;
};

interface AnimateParam {
    [Optional]
    attribute number duration;
};
// Improve: required for CallDrawModifierCallbacks in dummy_impl.cpp
[Synthetic]
callback Callback_DrawContext_Void = void (DrawContext drawContext);
[Entity=Class]
interface DrawModifier {
    constructor();
    [ExtraMethod=drawBehind, Accessor=Getter]
    attribute Callback_DrawContext_Void drawBehind_callback;
    [ExtraMethod=drawBehind, Accessor=Setter]
    attribute Callback_DrawContext_Void drawBehind_callback;
};

interface MenuElement {
    optional attribute CheckCustomModifierModifier modifierProp;
    optional attribute CheckTrivialModifierModifier trivialModifierProp;
};
