package arkui.component.datebook;
import arkui.stateManagement.runtime.memo as memo;
import arkui.stateManagement.runtime.ComponentBuilder as ComponentBuilder;
import arkui.component.common.CommonMethod as CommonMethod;

dictionary DatebookType {
    number EGYPTIAN = 0;
    number ROMAN = 1;
};
interface DatebookOptions {
    [Optional]
    attribute DatebookType type;
    [Optional]
    attribute boolean effect;
};
[Component]
interface DatebookAttribute: Root {
    attribute (DatebookType or undefined) type;
    attribute (String or undefined) text;

    // Fix Opt_CustomObject
    attribute (any or undefined) forceOptCustomObject;

    // generator hanging
    // attribute t: number
};
[Synthetic]
callback Callback_Void = void ();
[ComponentInterface]
interface DatebookInterface {
    [Annotations=memo, CallSignature]
    DatebookAttribute invoke(DatebookOptions label);
};