package arkui.component.enums;
dictionary TransitionType {
    [OriginalEnumMemberName=All]
    number ALL = 0;
    [OriginalEnumMemberName=Insert]
    number INSERT = 1;
    [OriginalEnumMemberName=Delete]
    number DELETE = 2;
};
dictionary InteractionHand {
    number NONE = 0;
    number LEFT = 1;
    number RIGHT = 2;
};