
test sdk api compat:
  allow_failure: true
  stage: test
  tags:
    - idlize-ci
  needs:
    - build idlize
  script:
    - !reference [.npm, script]
    - npm run download:sdk
    - node idlinter/bin/check-api-compat.mjs --idlize interface_sdk-js $CI_COMMIT_REF_NAME master

