package "org.openharmony.idlize.predefined.types";

interface Serializer {};
interface Deserializer {};
interface CallbackBuffer {};
interface CallbackResourceHolder {};
interface Tag {};
interface GENERATED_ArkUIEventsAPI {};
interface CallbackKind {};
