package raylib;

interface Color {
    attribute u8 r;
    attribute u8 g;
    attribute u8 b;
    attribute u8 a;
};

void InitWindow(i32 w, i32 h, String title);
void CloseWindow();
u8 WindowShouldClose();

u8 IsKeyPressed(i32 key);
u8 IsKeyDown(i32 key);

void BeginDrawing();
void EndDrawing();

void ClearBackground(Color color);
void DrawText(String text, i32 x, i32 y, i32 size, Color color);
void DrawRectangle(i32 posX, i32 posY, i32 width, i32 height, Color color);
void DrawCircle(i32 centerX, i32 centerY, f32 radius, Color color);
