package addon;

namespace floating {
    interface Size {
        attribute f32 height;
        attribute f32 width;
    };
    interface Sized {
        attribute Size size;
    };
    void resize(Size size);
};
