package main;

interface Size {
    attribute number height;
    attribute number width;
};
interface Sized {
    attribute Size size;
};

void resize(Size size);
void resizeInteger(integer.Size size);
void resizeFloating(floating.Size size);

namespace integer {
    interface Size {
        attribute i32 height;
        attribute i32 width;
    };
    interface Sized {
        attribute Size size;
    };
    void resize(Size size);
};
