
download koala_projects:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run download:koala_projects -C external
  artifacts:
    paths:
    - external/koala_projects

download interface_sdk-js:
  stage: build
  tags:
    - idlize-ci
    - koala-ci
  before_script:
    - !reference [.npm, script]
  script:
    - npm run download:interface_sdk-js -C external
  artifacts:
    paths:
    - external/interface_sdk-js
