package test_generic_interface;
[TypeParameters="T"]
interface GenericInterface {
    void setData(T data);
    void callHandler();
};
[TypeParameters="T"]
callback Callback_T_Void = void (T data);
[TypeParameters="T"]
interface GenericInterfaceDataHandler {
    attribute ([TypeArguments="void"] Callback_T_Void) onData;
};

[TypeParametersDefaults="void"]
callback <T, V> Callback = V (T data);

interface InterfaceWithVoidDataCallback {
    optional attribute Callback<void> onAppear;
};
