package test_constructor;

[Entity=Class]
interface IDLCheckConstructor {
    attribute number count;
    attribute boolean flag;
    constructor(number count);
    constructor(boolean flag);
    constructor(number count, boolean flag);
};
