/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package test_hilog;
interface ArgType {
    attribute number field;
};
namespace hilog {
    void debug(number domain, String tag, String format, sequence<ArgType> args);
    void info(number domain, String tag, String format, sequence<ArgType> args);
    void warn(number domain, String tag, String format, sequence<ArgType> args);
    void error(number domain, String tag, String format, sequence<ArgType> args);
    void fatal(number domain, String tag, String format, sequence<ArgType> args);
    boolean isLoggable(number domain, String tag, LogLevel level);
    void setMinLogLevel(LogLevel level);
    enum LogLevel {
        number DEBUG = 3;
        number INFO = 4;
        number WARN = 5;
        number ERROR = 6;
        number FATAL = 7;
    };
};