
package test_wrapped_builder;

[Synthetic]
callback Callback_WrappedBuilder_Args_Void = void (CommonConfiguration... args);

[Entity=Interface]
interface WrappedBuilder {
    attribute Callback_WrappedBuilder_Args_Void builder;
};

WrappedBuilder wrapBuilder(Callback_WrappedBuilder_Args_Void builder);

[Entity=Interface]
interface ContentModifier {
    WrappedBuilder applyContent();
};

[Entity=Interface]
interface CommonConfiguration {
    attribute boolean enabled;
    attribute ContentModifier contentModifier;
};