package test_length;
interface Resource {
    attribute number id;
    [Optional]
    attribute number type;
};
typedef Length = (String or number or Resource);
boolean testLength(number step, Length value);