/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package test_materialized_classes;
interface UtilityInterface {
    attribute String fieldString;
    attribute boolean fieldBoolean;
    attribute sequence<number> fieldArrayNumber;
};
namespace test_materialized_classes {
    [Entity=Class]
    interface StaticMaterialized {
        constructor();
        static void method(number valNumber, String valString);
    };
    [Entity=Class]
    interface MaterializedOverloadedMethods {
        constructor();
        void method1(optional boolean valBoolean, optional String valString);
    };
    [Entity=Class]
    interface MaterializedMoreOverloadedMethods: [Extends] MaterializedOverloadedMethods {
        constructor();
        void method2();
        void method2(number valNumber);
        void method2(number valNumber, String valString);
    };
    [Entity=Class]
    interface MaterializedWithConstructorAndFields: [Extends] MaterializedMoreOverloadedMethods {
        constructor(number valNumber, boolean valBoolean);
        attribute number valNumber;
        attribute boolean valBoolean;
    };
    [Entity=Class]
    interface MaterializedWithCreateMethod: [Extends] MaterializedWithConstructorAndFields {
        constructor();
        static MaterializedWithCreateMethod create(number valNumber, boolean valBoolean);
    };
    [Entity=Class]
    interface MaterializedComplexArguments: [Extends] MaterializedWithCreateMethod {
        constructor();
        UtilityInterface method3(UtilityInterface utilityInterface);
        sequence<String> method4(sequence<number> array);
        sequence<UtilityInterface> method5(sequence<UtilityInterface> arrayInterfaces);
    };
};