package test_external_types;
import external.lib.ExternalType as ExternalType;
import external.lib.hookns as hookns;
import external.lib.ExternalClass as ExternalClass;
import external.lib.ExternalModuleDataInterface as ExternalModuleDataInterface;
interface InternalType {
    attribute number index;
};
[Entity=Class]
interface DTSCheckExternalLib {
    constructor();
    number checkExternalDataInterface(ExternalModuleDataInterface externalType);
    void checkExternalType(ExternalType externalType);
    void checkExternalClass(ExternalClass externalClass);
    void checkNSExternalType(hookns.NSExternalType externalType);
    void checkSubNSExternalType(hookns.subhookns.SubNSExternalType externalType);
};