package test_union;

dictionary UnionSampleEnum {
    number A = 0;
    number B = 1;
    number C = 10;
    number D = 11;
};

[Entity=Tuple, Synthetic]
interface UnionSampleTupleNumberString {
    attribute number value0;
    attribute String value1;
};

interface <T> SingleGenericType {
    readonly attribute T value;
};

interface <T, S> DoubleGenericType {
    readonly attribute T valueT;
    readonly attribute S valueS;
};

[Entity=Interface]
interface UnionSampleEnumInterface {

    attribute (number or UnionSampleEnum) prop;
};

[Entity=Interface]
interface UnionSampleArrayInterface {

    attribute (boolean or number or String or UnionSampleEnum or sequence<boolean> or sequence<UnionSampleEnum>) prop;
};

[Entity=Interface]
interface UnionSampleNumberArrayInterface {

    attribute (number or sequence<number>) prop;
};

[Entity=Interface]
interface UnionSampleTupleArrayInterface {

    attribute (number or String or UnionSampleTupleNumberString or sequence<UnionSampleTupleNumberString>) prop;
};

[Entity=Interface]
interface UnionSampleGenericTypeInterface {
    attribute (number or String or SingleGenericType<number> or SingleGenericType<String> or DoubleGenericType<boolean, number> or DoubleGenericType<number, String>) prop;
};

UnionSampleEnumInterface checkUnionEnumSample(UnionSampleEnumInterface value);
UnionSampleArrayInterface checkUnionArraySample(UnionSampleArrayInterface value);
UnionSampleNumberArrayInterface checkUnionNumberArraySample(UnionSampleNumberArrayInterface value);
UnionSampleTupleArrayInterface checkUnionTupleArraySample(UnionSampleTupleArrayInterface value);
UnionSampleGenericTypeInterface checkUnionGenericTypeSample(UnionSampleGenericTypeInterface value);
