package test_optional;

interface TestOptional {
    attribute number value;
    optional attribute number optValue;
};

number sumOptionalAttributes(TestOptional arg);
number idOrZero(optional number arg);
