package test_data_interface;
[Entity=Tuple, Synthetic]
interface Tuple_Boolean_Number_String {
    attribute boolean value0;
    attribute number value1;
    attribute String value2;
};
interface DataInterface {
    attribute boolean propBoolean;
    attribute number propNumber;
    attribute String propString;
    attribute Tuple_Boolean_Number_String propObject;
};
[Entity=Class]
interface DataClass: DataInterface {
    constructor();
    [Accessor=Getter]
    attribute boolean propBoolean;
    [Accessor=Setter]
    attribute boolean propBoolean;
    [Accessor=Getter]
    attribute number propNumber;
    [Accessor=Setter]
    attribute number propNumber;
    [Accessor=Getter]
    attribute String propString;
    [Accessor=Setter]
    attribute String propString;
    [Accessor=Getter]
    attribute Tuple_Boolean_Number_String propObject;
    [Accessor=Setter]
    attribute Tuple_Boolean_Number_String propObject;
};
DataInterface testDataInterface(DataInterface arg);
DataClass testDataClass(DataClass arg);