package test_hooks;
import external.lib.ImportedHookValue as ImportedHookValue;

interface HookValue {
    attribute number count;
};

interface HookInterface {
    void method();
    void methodArg(HookValue value);
    HookValue methodReturn();
    void methodImportedArg(ImportedHookValue hookedValue);
    ImportedHookValue methodImportedReturn();
};

HookInterface getHookInterface();

[Entity=Class]
interface HookClass {
    constructor();
    void method();
    void methodArg(HookValue value);
    HookValue methodReturn();
    void methodImportedArg(ImportedHookValue hookedValue);
    ImportedHookValue methodImportedReturn();
};