package test_enum;
dictionary OrdinaryEnum {
    number E1;
    number E2;
    number E3;
};
dictionary IntEnum {
    number E1 = 11;
    number E3 = 33;
    number E5 = 55;
};

dictionary DuplicateIntEnum {
    number FIRST = 0;
    [OriginalEnumMemberName=first]
    number LEGACY_FIRST = 0;
    number SECOND = 1;
    [OriginalEnumMemberName=second]
    number LEGACY_SECOND = 1;
    number THIRD = 2;
    [OriginalEnumMemberName=third]
    number LEGACY_THIRD = 2;
};
dictionary StringEnum {
    [OriginalEnumMemberName=e1]
    String E1 = "e11";
    [OriginalEnumMemberName=e2]
    String E2 = "e22";
    String E_MIDDLE = "eMiddle";
    [OriginalEnumMemberName=e3]
    String E3 = "e33";
};
OrdinaryEnum checkOrdinaryEnums(OrdinaryEnum value1, OrdinaryEnum value2);
IntEnum checkIntEnums(IntEnum value1, IntEnum value2);
DuplicateIntEnum checkDuplicateIntEnums(DuplicateIntEnum value1, DuplicateIntEnum value2);
StringEnum checkStringEnums(StringEnum value1, StringEnum value2);
StringEnum checkStringEnumOrdinal(StringEnum value, i32 expectedOrdinal);

dictionary IntEnum255 {
    number E1 = 1;
    number E255 = 255;
};

dictionary IntEnum256 {
    number E1 = 1;
    number E256 = 256;
};

dictionary IntEnum257 {
    number E1 = 1;
    number E257 = 257;
};
