package test_generics;
namespace generics {
    [TypeParameters="A,B"]
    interface Y {
        A bar(B y);
    };
    [TypeParameters="A,B,C", TypeParametersDefaults="number,void"]
    interface X: [TypeArguments="A,B"] Y {
        C foo(A x, B y);
    };

    [TypeParametersDefaults="number"]
    interface <T> WithDefaultsA {
        attribute T value;
    };
    // validate that generics default are also applied to TypeParametersDefaults items
    [TypeParametersDefaults="WithDefaultsA"]
    interface <T> WithDefaultsB {
        attribute T value;
    };
    void callWithDefaultsB(WithDefaultsB value);
};