/*
 * Copyright (c) 2026 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package constants;
const boolean CONST_BOOLEAN_FALSE = false;
const boolean CONST_BOOLEAN_TRUE = true;
const number CONST_NUMBER_INT = 312;
const number CONST_NUMBER_FLOAT = 312.415;
const String CONST_STRING = "hello_string";
const boolean CONST_TYPE_BOOLEAN;
const number CONST_TYPE_NUMBER;
const f32 CONST_TYPE_FLOAT;
const String CONST_TYPE_STRING;
namespace const_ns {
    const boolean CONST_BOOLEAN_FALSE = false;
    const boolean CONST_BOOLEAN_TRUE = true;
    const number CONST_NUMBER_INT = 312;
    const number CONST_NUMBER_FLOAT = 312.415;
    const String CONST_STRING = "hello_string";
    const boolean CONST_TYPE_BOOLEAN;
    const number CONST_TYPE_NUMBER;
    const f32 CONST_TYPE_FLOAT;
    const String CONST_TYPE_STRING;
};