package enum;
enum EnumWithoutInitializers {
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0;
    [OriginalEnumMemberName=Value2]
    number VALUE_2 = 1;
};
enum NumberEnum {
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0;
    [OriginalEnumMemberName=Value2]
    number VALUE_2 = 1;
    [OriginalEnumMemberName=Value3]
    number VALUE_3 = 3;
    [OriginalEnumMemberName=Value4]
    number VALUE_4 = 8;
    [OriginalEnumMemberName=Value5]
    number VALUE_5 = 9;
    [OriginalEnumMemberName=Value6]
    number VALUE_6 = 13;
};
enum BinaryEnum {
    [OriginalEnumMemberName=Value0]
    number VALUE_0 = 0b0;
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0b1;
    [OriginalEnumMemberName=Value101]
    number VALUE_101 = 0b101;
    [OriginalEnumMemberName=Value1001]
    number VALUE_1001 = 0b1001;
};
enum HexEnum {
    [OriginalEnumMemberName=Value0]
    number VALUE_0 = 0x0;
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0x1;
    [OriginalEnumMemberName=ValueAB]
    number VALUE_AB = 0xAB;
    [OriginalEnumMemberName=ValueCD]
    number VALUE_CD = 0xCD;
    [OriginalEnumMemberName=ValueFFFFFFFF]
    number VALUE_FFFFFFFF = 0xFFFFFFFF;
};
enum StringEnum {
    [OriginalEnumMemberName=Value1]
    String VALUE_1 = "one";
    [OriginalEnumMemberName=Value2]
    String VALUE_2 = "two";
    [OriginalEnumMemberName=Value2]
    String LEGACY_VALUE_2 = "three";
};
namespace ns {
    enum EnumInNamespace {
        [OriginalEnumMemberName=Value1]
        String VALUE_1 = "one";
        [OriginalEnumMemberName=Value2]
        String VALUE_2 = "two";
        [OriginalEnumMemberName=Value2]
        String LEGACY_VALUE_2 = "three";
    };
};
enum ShiftEnum {
    [OriginalEnumMemberName=Value0]
    number VALUE_0 = 0x1;
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0x2;
    [OriginalEnumMemberName=Value2]
    number VALUE_2 = 0x44;
    [OriginalEnumMemberName=Value3]
    number VALUE_3 = 0x1;
    [OriginalEnumMemberName=Value4]
    number VALUE_4 = 0x3;
    [OriginalEnumMemberName=Value5]
    number VALUE_5 = 0x1;
    [OriginalEnumMemberName=Value6]
    number VALUE_6 = 0x2;
    [OriginalEnumMemberName=Value7]
    number VALUE_7 = 0x4;
    [OriginalEnumMemberName=Value8]
    number VALUE_8 = 0x2;
    [OriginalEnumMemberName=Value9]
    number VALUE_9 = 0x6;
    [OriginalEnumMemberName=Value10]
    number VALUE_10 = 0x3;
    [OriginalEnumMemberName=Value11]
    number VALUE_11 = 0x9;
    [OriginalEnumMemberName=Value11]
    number undefined = 0x7;
    [OriginalEnumMemberName=Value11]
    number LEGACY_VALUE_11 = 0x5;
};