package enum;
dictionary EnumWithoutInitializers {
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0;
    [OriginalEnumMemberName=Value2]
    number VALUE_2 = 1;
};
dictionary NumberEnum {
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 0;
    [OriginalEnumMemberName=Value2]
    number VALUE_2 = 1;
    [OriginalEnumMemberName=Value3]
    number VALUE_3 = 3;
    [OriginalEnumMemberName=Value4]
    number VALUE_4 = 8;
    [OriginalEnumMemberName=Value5]
    number VALUE_5 = 9;
    [OriginalEnumMemberName=Value6]
    number VALUE_6 = 13;
};
dictionary BinaryEnum {
    [OriginalEnumMemberName=Value0]
    number VALUE_0 = 0;
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 1;
    [OriginalEnumMemberName=Value101]
    number VALUE_101 = 5;
    [OriginalEnumMemberName=Value1001]
    number VALUE_1001 = 9;
};
dictionary HexEnum {
    [OriginalEnumMemberName=Value0]
    number VALUE_0 = 0;
    [OriginalEnumMemberName=Value1]
    number VALUE_1 = 1;
    [OriginalEnumMemberName=ValueAB]
    number VALUE_AB = 171;
    [OriginalEnumMemberName=ValueCD]
    number VALUE_CD = 205;
};
dictionary StringEnum {
    [OriginalEnumMemberName=Value1]
    String VALUE_1 = "one";
    [OriginalEnumMemberName=Value2]
    String VALUE_2 = "two";
    [OriginalEnumMemberName=Value2]
    String LEGACY_VALUE_2 = "three";
};
namespace ns {
    dictionary EnumInNamespace {
        [OriginalEnumMemberName=Value1]
        String VALUE_1 = "one";
        [OriginalEnumMemberName=Value2]
        String VALUE_2 = "two";
        [OriginalEnumMemberName=Value2]
        String LEGACY_VALUE_2 = "three";
    };
};