package force_callback;
[Synthetic]
callback Callback_String_Void = void (String value);
interface EditMenuOptions {
    attribute Callback_String_Void onCreateMenu;
    [ExtraMethod=onCreateMenuExtraMethod]
    attribute Callback_String_Void onCreateMenuExtraMethod_callback;
};