package primitives;
interface Iface {
    void foo(any value);
    this foo();
    void foo(Object value);
    void foo((String or undefined) value);
    void foo(number value);
    void foo(i32 value);
    void foo(f32 value);
    void foo(i64 value);
    void foo(i16 value);
    void foo(f64 value);
    void foo(boolean value);
    void foo(u16 value);
    void foo(sequence<String> value);
    void foo();
    void foo(record<String, number> value);
    void foo(date value);
    void foo(buffer value);
    void foo((String or undefined) value);
};