package throws;
interface ThrowableInterface {
    [Throws]
    void foo();
    [Throws]
    void fizz();
};
[Entity=Class]
interface ThrowableClass {
    constructor();
    [Throws]
    void boo();
    [Throws]
    void buzz();
};